#define PHQL_AGAINST                          1
#define PHQL_BETWEEN                          2
#define PHQL_EQUALS                           3
#define PHQL_NOTEQUALS                        4
#define PHQL_LESS                             5
#define PHQL_GREATER                          6
#define PHQL_GREATEREQUAL                     7
#define PHQL_LESSEQUAL                        8
#define PHQL_TS_MATCHES                       9
#define PHQL_TS_OR                           10
#define PHQL_TS_AND                          11
#define PHQL_TS_NEGATE                       12
#define PHQL_TS_CONTAINS_ANOTHER             13
#define PHQL_TS_CONTAINS_IN                  14
#define PHQL_AND                             15
#define PHQL_OR                              16
#define PHQL_LIKE                            17
#define PHQL_ILIKE                           18
#define PHQL_BITWISE_AND                     19
#define PHQL_BITWISE_OR                      20
#define PHQL_BITWISE_XOR                     21
#define PHQL_DIVIDE                          22
#define PHQL_TIMES                           23
#define PHQL_MOD                             24
#define PHQL_PLUS                            25
#define PHQL_MINUS                           26
#define PHQL_IS                              27
#define PHQL_DOUBLECOLON                     28
#define PHQL_IN                              29
#define PHQL_NOT                             30
#define PHQL_BITWISE_NOT                     31
#define PHQL_FORCE                           32
#define PHQL_USE                             33
#define PHQL_COMMA                           34
#define PHQL_SELECT                          35
#define PHQL_FROM                            36
#define PHQL_DISTINCT                        37
#define PHQL_ALL                             38
#define PHQL_IDENTIFIER                      39
#define PHQL_DOT                             40
#define PHQL_AS                              41
#define PHQL_INNER                           42
#define PHQL_JOIN                            43
#define PHQL_CROSS                           44
#define PHQL_LEFT                            45
#define PHQL_OUTER                           46
#define PHQL_RIGHT                           47
#define PHQL_FULL                            48
#define PHQL_ON                              49
#define PHQL_PARENTHESES_OPEN                50
#define PHQL_PARENTHESES_CLOSE               51
#define PHQL_INSERT                          52
#define PHQL_INTO                            53
#define PHQL_VALUES                          54
#define PHQL_UPDATE                          55
#define PHQL_SET                             56
#define PHQL_DELETE                          57
#define PHQL_IGNORE                          58
#define PHQL_INDEX                           59
#define PHQL_WHERE                           60
#define PHQL_ORDER                           61
#define PHQL_BY                              62
#define PHQL_ASC                             63
#define PHQL_DESC                            64
#define PHQL_GROUP                           65
#define PHQL_HAVING                          66
#define PHQL_FOR                             67
#define PHQL_LIMIT                           68
#define PHQL_OFFSET                          69
#define PHQL_INTEGER                         70
#define PHQL_HINTEGER                        71
#define PHQL_NPLACEHOLDER                    72
#define PHQL_SPLACEHOLDER                    73
#define PHQL_EXISTS                          74
#define PHQL_CAST                            75
#define PHQL_CONVERT                         76
#define PHQL_USING                           77
#define PHQL_CASE                            78
#define PHQL_END                             79
#define PHQL_WHEN                            80
#define PHQL_THEN                            81
#define PHQL_ELSE                            82
#define PHQL_NULL                            83
#define PHQL_STRING                          84
#define PHQL_DOUBLE                          85
#define PHQL_TRUE                            86
#define PHQL_FALSE                           87
#define PHQL_BPLACEHOLDER                    88
#define PHQL_COLON                           89
