/* Generated by re2c 0.13.5 on Fri Jun 26 10:19:24 2015 */
/* #line 1 "scanner.re" */

/*
  +------------------------------------------------------------------------+
  | Phalcon Framework                                                      |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2014 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  +------------------------------------------------------------------------+
*/

#include "php_phalcon.h"

#include "mvc/model/query/scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int phql_get_token(phql_scanner_state *s, phql_scanner_token *token) {

	char *q = YYCURSOR;
	int status = PHQL_SCANNER_RETCODE_IMPOSSIBLE;

	while (PHQL_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
/* #line 40 "scanner.c" */
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;
			static const unsigned char yybm[] = {
				  0,  12,  12,  12,  12,  12,  12,  12, 
				 12,  13,  13,  12,  12,  13,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 13,  12,   4,  12,  12,  12,  12,   8, 
				 12,  12,  12,  12,  12,  60,  12,  12, 
				254, 254, 254, 254, 254, 254, 254, 254, 
				254, 254,  30,  12,  12,  12,  12,  12, 
				 12, 190, 190, 190, 190, 190, 190, 190, 
				190, 190, 190, 190, 190, 190, 190, 190, 
				190, 190, 190, 190, 190, 190, 190, 190, 
				190, 190, 190,  12,   2,  12,  12,  62, 
				 12, 190, 190, 190, 190, 190, 190, 190, 
				190, 190, 190, 190, 190, 190, 190, 190, 
				190, 190, 190, 190, 190, 190, 190, 190, 
				190, 190, 190,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
				 12,  12,  12,  12,  12,  12,  12,  12, 
			};

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy72;
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy70;
			case '!':	goto yy53;
			case '"':	goto yy32;
			case '%':	goto yy45;
			case '&':	goto yy64;
			case '\'':	goto yy33;
			case '(':	goto yy49;
			case ')':	goto yy51;
			case '*':	goto yy41;
			case '+':	goto yy37;
			case ',':	goto yy47;
			case '-':	goto yy39;
			case '.':	goto yy5;
			case '/':	goto yy43;
			case '0':	goto yy2;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy4;
			case ':':	goto yy9;
			case '<':	goto yy55;
			case '=':	goto yy59;
			case '>':	goto yy57;
			case '?':	goto yy7;
			case '@':	goto yy61;
			case 'A':
			case 'a':	goto yy17;
			case 'B':
			case 'b':	goto yy22;
			case 'C':
			case 'c':	goto yy29;
			case 'D':
			case 'd':	goto yy15;
			case 'E':
			case 'e':	goto yy30;
			case 'F':
			case 'f':	goto yy16;
			case 'G':
			case 'g':	goto yy23;
			case 'H':
			case 'h':	goto yy24;
			case 'I':
			case 'i':	goto yy18;
			case 'J':
			case 'j':	goto yy27;
			case 'K':
			case 'M':
			case 'P':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'k':
			case 'm':
			case 'p':
			case 'q':
			case 'x':
			case 'y':
			case 'z':	goto yy35;
			case 'L':
			case 'l':	goto yy25;
			case 'N':
			case 'n':	goto yy26;
			case 'O':
			case 'o':	goto yy21;
			case 'R':
			case 'r':	goto yy28;
			case 'S':
			case 's':	goto yy14;
			case 'T':
			case 't':	goto yy31;
			case 'U':
			case 'u':	goto yy12;
			case 'V':
			case 'v':	goto yy19;
			case 'W':
			case 'w':	goto yy20;
			case '[':	goto yy36;
			case '\\':	goto yy34;
			case '^':	goto yy68;
			case '{':	goto yy11;
			case '|':	goto yy62;
			case '~':	goto yy66;
			default:	goto yy74;
			}
yy2:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= '/') {
				if (yych == '.') goto yy333;
			} else {
				if (yych <= '9') goto yy335;
				if (yych == 'x') goto yy337;
			}
yy3:
/* #line 50 "scanner.re" */
			{
			token->opcode = PHQL_T_INTEGER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 194 "scanner.c" */
yy4:
			yych = *++YYCURSOR;
			if (yych == '.') goto yy333;
			if (yych <= '/') goto yy3;
			if (yych <= '9') goto yy335;
			goto yy3;
yy5:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '/') goto yy6;
			if (yych <= '9') goto yy330;
yy6:
/* #line 406 "scanner.re" */
			{
			token->opcode = PHQL_T_DOT;
			return 0;
		}
/* #line 211 "scanner.c" */
yy7:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 64) {
				goto yy327;
			}
yy8:
/* #line 531 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_ERR;
			break;
		}
/* #line 223 "scanner.c" */
yy9:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 32) {
				goto yy323;
			}
yy10:
/* #line 411 "scanner.re" */
			{
			token->opcode = PHQL_T_COLON;
			return 0;
		}
/* #line 236 "scanner.c" */
yy11:
			yyaccept = 2;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 16) {
				goto yy319;
			}
			goto yy8;
yy12:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= 'S') {
				if (yych == 'P') goto yy308;
				if (yych <= 'R') goto yy101;
				goto yy309;
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy101;
					goto yy308;
				} else {
					if (yych == 's') goto yy309;
					goto yy101;
				}
			}
yy13:
/* #line 354 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			if ((YYCURSOR - q) > 1) {
				if (q[0] == '\\') {
					token->value = estrndup(q + 1, YYCURSOR - q - 1);
					token->len = YYCURSOR - q - 1;
				} else {
					token->value = estrndup(q, YYCURSOR - q);
					token->len = YYCURSOR - q;
				}
			} else {
				token->value = estrndup(q, YYCURSOR - q);
				token->len = YYCURSOR - q;
			}
			q = YYCURSOR;
			return 0;
		}
/* #line 278 "scanner.c" */
yy14:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy300;
			if (yych == 'e') goto yy300;
			goto yy101;
yy15:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy283;
				if (yych <= 'H') goto yy101;
				goto yy284;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy101;
					goto yy283;
				} else {
					if (yych == 'i') goto yy284;
					goto yy101;
				}
			}
yy16:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'O') {
					if (yych == 'A') goto yy267;
					if (yych <= 'N') goto yy101;
					goto yy268;
				} else {
					if (yych == 'R') goto yy269;
					if (yych <= 'T') goto yy101;
					goto yy270;
				}
			} else {
				if (yych <= 'o') {
					if (yych == 'a') goto yy267;
					if (yych <= 'n') goto yy101;
					goto yy268;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy101;
						goto yy269;
					} else {
						if (yych == 'u') goto yy270;
						goto yy101;
					}
				}
			}
yy17:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'L') {
					if (yych == 'G') goto yy250;
					if (yych <= 'K') goto yy101;
					goto yy251;
				} else {
					if (yych == 'N') goto yy252;
					if (yych <= 'R') goto yy101;
					goto yy253;
				}
			} else {
				if (yych <= 'l') {
					if (yych == 'g') goto yy250;
					if (yych <= 'k') goto yy101;
					goto yy251;
				} else {
					if (yych <= 'n') {
						if (yych <= 'm') goto yy101;
						goto yy252;
					} else {
						if (yych == 's') goto yy253;
						goto yy101;
					}
				}
			}
yy18:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy229;
					goto yy101;
				} else {
					if (yych <= 'N') goto yy230;
					if (yych <= 'R') goto yy101;
					goto yy232;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy229;
					goto yy101;
				} else {
					if (yych <= 'n') goto yy230;
					if (yych == 's') goto yy232;
					goto yy101;
				}
			}
yy19:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy223;
			if (yych == 'a') goto yy223;
			goto yy101;
yy20:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy216;
			if (yych == 'h') goto yy216;
			goto yy101;
yy21:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'N') {
					if (yych == 'F') goto yy197;
					if (yych <= 'M') goto yy101;
					goto yy198;
				} else {
					if (yych == 'R') goto yy200;
					if (yych <= 'T') goto yy101;
					goto yy202;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'f') goto yy197;
					if (yych <= 'm') goto yy101;
					goto yy198;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy101;
						goto yy200;
					} else {
						if (yych == 'u') goto yy202;
						goto yy101;
					}
				}
			}
yy22:
			yych = *++YYCURSOR;
			if (yych <= 'Y') {
				if (yych == 'E') goto yy188;
				if (yych <= 'X') goto yy101;
				goto yy189;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy101;
					goto yy188;
				} else {
					if (yych == 'y') goto yy189;
					goto yy101;
				}
			}
yy23:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy183;
			if (yych == 'r') goto yy183;
			goto yy101;
yy24:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy177;
			if (yych == 'a') goto yy177;
			goto yy101;
yy25:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy165;
				if (yych <= 'H') goto yy101;
				goto yy166;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy101;
					goto yy165;
				} else {
					if (yych == 'i') goto yy166;
					goto yy101;
				}
			}
yy26:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych == 'O') goto yy158;
				if (yych <= 'T') goto yy101;
				goto yy159;
			} else {
				if (yych <= 'o') {
					if (yych <= 'n') goto yy101;
					goto yy158;
				} else {
					if (yych == 'u') goto yy159;
					goto yy101;
				}
			}
yy27:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy154;
			if (yych == 'o') goto yy154;
			goto yy101;
yy28:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy149;
			if (yych == 'i') goto yy149;
			goto yy101;
yy29:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych <= 'N') {
					if (yych == 'A') goto yy131;
					goto yy101;
				} else {
					if (yych <= 'O') goto yy132;
					if (yych <= 'Q') goto yy101;
					goto yy133;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'a') goto yy131;
					goto yy101;
				} else {
					if (yych <= 'o') goto yy132;
					if (yych == 'r') goto yy133;
					goto yy101;
				}
			}
yy30:
			yych = *++YYCURSOR;
			if (yych <= 'X') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy118;
					goto yy101;
				} else {
					if (yych <= 'N') goto yy119;
					if (yych <= 'W') goto yy101;
					goto yy120;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy118;
					goto yy101;
				} else {
					if (yych <= 'n') goto yy119;
					if (yych == 'x') goto yy120;
					goto yy101;
				}
			}
yy31:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'H') goto yy110;
				if (yych <= 'Q') goto yy101;
				goto yy111;
			} else {
				if (yych <= 'h') {
					if (yych <= 'g') goto yy101;
					goto yy110;
				} else {
					if (yych == 'r') goto yy111;
					goto yy101;
				}
			}
yy32:
			yyaccept = 2;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy8;
			goto yy108;
yy33:
			yyaccept = 2;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy8;
			goto yy103;
yy34:
			yych = *++YYCURSOR;
			if (yych <= '^') {
				if (yych <= '@') goto yy8;
				if (yych <= 'Z') goto yy100;
				goto yy8;
			} else {
				if (yych == '`') goto yy8;
				if (yych <= 'z') goto yy100;
				goto yy8;
			}
yy35:
			yych = *++YYCURSOR;
			goto yy101;
yy36:
			yyaccept = 2;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= '\\') {
				if (yych <= '@') goto yy8;
				if (yych == '[') goto yy8;
				goto yy95;
			} else {
				if (yych <= '_') {
					if (yych <= '^') goto yy8;
					goto yy95;
				} else {
					if (yych <= '`') goto yy8;
					if (yych <= 'z') goto yy95;
					goto yy8;
				}
			}
yy37:
			++YYCURSOR;
/* #line 381 "scanner.re" */
			{
			token->opcode = PHQL_T_ADD;
			return 0;
		}
/* #line 581 "scanner.c" */
yy39:
			++YYCURSOR;
/* #line 386 "scanner.re" */
			{
			token->opcode = PHQL_T_SUB;
			return 0;
		}
/* #line 589 "scanner.c" */
yy41:
			++YYCURSOR;
/* #line 391 "scanner.re" */
			{
			token->opcode = PHQL_T_MUL;
			return 0;
		}
/* #line 597 "scanner.c" */
yy43:
			++YYCURSOR;
/* #line 396 "scanner.re" */
			{
			token->opcode = PHQL_T_DIV;
			return 0;
		}
/* #line 605 "scanner.c" */
yy45:
			++YYCURSOR;
/* #line 401 "scanner.re" */
			{
			token->opcode = PHQL_T_MOD;
			return 0;
		}
/* #line 613 "scanner.c" */
yy47:
			++YYCURSOR;
/* #line 416 "scanner.re" */
			{
			token->opcode = PHQL_T_COMMA;
			return 0;
		}
/* #line 621 "scanner.c" */
yy49:
			++YYCURSOR;
/* #line 421 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_OPEN;
			return 0;
		}
/* #line 629 "scanner.c" */
yy51:
			++YYCURSOR;
/* #line 426 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_CLOSE;
			return 0;
		}
/* #line 637 "scanner.c" */
yy53:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '!') goto yy91;
			if (yych == '=') goto yy93;
/* #line 496 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 647 "scanner.c" */
yy55:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '<') goto yy56;
			if (yych <= '=') goto yy87;
			if (yych <= '>') goto yy89;
yy56:
/* #line 451 "scanner.re" */
			{
			token->opcode = PHQL_T_LESS;
			return 0;
		}
/* #line 659 "scanner.c" */
yy57:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '=') goto yy85;
/* #line 456 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATER;
			return 0;
		}
/* #line 668 "scanner.c" */
yy59:
			++YYCURSOR;
/* #line 461 "scanner.re" */
			{
			token->opcode = PHQL_T_EQUALS;
			return 0;
		}
/* #line 676 "scanner.c" */
yy61:
			yych = *++YYCURSOR;
			if (yych == '>') goto yy81;
			if (yych == '@') goto yy83;
			goto yy8;
yy62:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '|') goto yy79;
/* #line 516 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_OR;
			return 0;
		}
/* #line 690 "scanner.c" */
yy64:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '&') goto yy77;
/* #line 511 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_AND;
			return 0;
		}
/* #line 699 "scanner.c" */
yy66:
			++YYCURSOR;
/* #line 501 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_NOT;
			return 0;
		}
/* #line 707 "scanner.c" */
yy68:
			++YYCURSOR;
/* #line 506 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_XOR;
			return 0;
		}
/* #line 715 "scanner.c" */
yy70:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy76;
yy71:
/* #line 521 "scanner.re" */
			{
			token->opcode = PHQL_T_IGNORE;
			return 0;
		}
/* #line 726 "scanner.c" */
yy72:
			++YYCURSOR;
/* #line 526 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_EOF;
			break;
		}
/* #line 734 "scanner.c" */
yy74:
			yych = *++YYCURSOR;
			goto yy8;
yy75:
			++YYCURSOR;
			yych = *YYCURSOR;
yy76:
			if (yybm[0+yych] & 1) {
				goto yy75;
			}
			goto yy71;
yy77:
			++YYCURSOR;
/* #line 476 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_AND;
			return 0;
		}
/* #line 753 "scanner.c" */
yy79:
			++YYCURSOR;
/* #line 471 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_OR;
			return 0;
		}
/* #line 761 "scanner.c" */
yy81:
			++YYCURSOR;
/* #line 486 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_CONTAINS_ANOTHER;
			return 0;
		}
/* #line 769 "scanner.c" */
yy83:
			++YYCURSOR;
/* #line 466 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_MATCHES;
			return 0;
		}
/* #line 777 "scanner.c" */
yy85:
			++YYCURSOR;
/* #line 446 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATEREQUAL;
			return 0;
		}
/* #line 785 "scanner.c" */
yy87:
			++YYCURSOR;
/* #line 441 "scanner.re" */
			{
			token->opcode = PHQL_T_LESSEQUAL;
			return 0;
		}
/* #line 793 "scanner.c" */
yy89:
			++YYCURSOR;
/* #line 436 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 801 "scanner.c" */
yy91:
			++YYCURSOR;
/* #line 481 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_NEGATE;
			return 0;
		}
/* #line 809 "scanner.c" */
yy93:
			++YYCURSOR;
/* #line 431 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 817 "scanner.c" */
yy95:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 2) {
				goto yy95;
			}
			if (yych == ']') goto yy98;
yy97:
			YYCURSOR = YYMARKER;
			if (yyaccept <= 1) {
				if (yyaccept <= 0) {
					goto yy3;
				} else {
					goto yy10;
				}
			} else {
				goto yy8;
			}
yy98:
			++YYCURSOR;
/* #line 373 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 846 "scanner.c" */
yy100:
			++YYCURSOR;
			yych = *YYCURSOR;
yy101:
			if (yych <= '[') {
				if (yych <= ':') {
					if (yych <= '/') goto yy13;
					goto yy100;
				} else {
					if (yych <= '@') goto yy13;
					if (yych <= 'Z') goto yy100;
					goto yy13;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych <= '^') goto yy13;
					goto yy100;
				} else {
					if (yych <= '`') goto yy13;
					if (yych <= 'z') goto yy100;
					goto yy13;
				}
			}
yy102:
			++YYCURSOR;
			yych = *YYCURSOR;
yy103:
			if (yybm[0+yych] & 4) {
				goto yy102;
			}
			if (yych <= 0x00) goto yy97;
			if (yych <= '[') goto yy105;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy97;
			goto yy102;
yy105:
			++YYCURSOR;
/* #line 345 "scanner.re" */
			{
			token->opcode = PHQL_T_STRING;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 894 "scanner.c" */
yy107:
			++YYCURSOR;
			yych = *YYCURSOR;
yy108:
			if (yybm[0+yych] & 8) {
				goto yy107;
			}
			if (yych <= 0x00) goto yy97;
			if (yych <= '[') goto yy105;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy97;
			goto yy107;
yy110:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy115;
			if (yych == 'e') goto yy115;
			goto yy101;
yy111:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy112;
			if (yych != 'u') goto yy101;
yy112:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy113;
			if (yych != 'e') goto yy101;
yy113:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy114;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy114;
					if (yych <= 'z') goto yy100;
				}
			}
yy114:
/* #line 304 "scanner.re" */
			{
			token->opcode = PHQL_T_TRUE;
			return 0;
		}
/* #line 945 "scanner.c" */
yy115:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy116;
			if (yych != 'n') goto yy101;
yy116:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy117;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy117;
					if (yych <= 'z') goto yy100;
				}
			}
yy117:
/* #line 329 "scanner.re" */
			{
			token->opcode = PHQL_T_THEN;
			return 0;
		}
/* #line 974 "scanner.c" */
yy118:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy128;
			if (yych == 's') goto yy128;
			goto yy101;
yy119:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy126;
			if (yych == 'd') goto yy126;
			goto yy101;
yy120:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy121;
			if (yych != 'i') goto yy101;
yy121:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy122;
			if (yych != 's') goto yy101;
yy122:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy123;
			if (yych != 't') goto yy101;
yy123:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy124;
			if (yych != 's') goto yy101;
yy124:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy125;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy125;
					if (yych <= 'z') goto yy100;
				}
			}
yy125:
/* #line 299 "scanner.re" */
			{
			token->opcode = PHQL_T_EXISTS;
			return 0;
		}
/* #line 1025 "scanner.c" */
yy126:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy127;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy127;
					if (yych <= 'z') goto yy100;
				}
			}
yy127:
/* #line 339 "scanner.re" */
			{
			token->opcode = PHQL_T_END;
			return 0;
		}
/* #line 1050 "scanner.c" */
yy128:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy129;
			if (yych != 'e') goto yy101;
yy129:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy130;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy130;
					if (yych <= 'z') goto yy100;
				}
			}
yy130:
/* #line 334 "scanner.re" */
			{
			token->opcode = PHQL_T_ELSE;
			return 0;
		}
/* #line 1079 "scanner.c" */
yy131:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy144;
			if (yych == 's') goto yy144;
			goto yy101;
yy132:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy138;
			if (yych == 'n') goto yy138;
			goto yy101;
yy133:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy134;
			if (yych != 'o') goto yy101;
yy134:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy135;
			if (yych != 's') goto yy101;
yy135:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy136;
			if (yych != 's') goto yy101;
yy136:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy137;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy137;
					if (yych <= 'z') goto yy100;
				}
			}
yy137:
/* #line 244 "scanner.re" */
			{
			token->opcode = PHQL_T_CROSS;
			return 0;
		}
/* #line 1126 "scanner.c" */
yy138:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy139;
			if (yych != 'v') goto yy101;
yy139:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy140;
			if (yych != 'e') goto yy101;
yy140:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy141;
			if (yych != 'r') goto yy101;
yy141:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy142;
			if (yych != 't') goto yy101;
yy142:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy143;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy143;
					if (yych <= 'z') goto yy100;
				}
			}
yy143:
/* #line 289 "scanner.re" */
			{
			token->opcode = PHQL_T_CONVERT;
			return 0;
		}
/* #line 1167 "scanner.c" */
yy144:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'E') goto yy145;
				if (yych <= 'S') goto yy101;
				goto yy147;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy101;
				} else {
					if (yych == 't') goto yy147;
					goto yy101;
				}
			}
yy145:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy146;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy146;
					if (yych <= 'z') goto yy100;
				}
			}
yy146:
/* #line 319 "scanner.re" */
			{
			token->opcode = PHQL_T_CASE;
			return 0;
		}
/* #line 1206 "scanner.c" */
yy147:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy148;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy148;
					if (yych <= 'z') goto yy100;
				}
			}
yy148:
/* #line 284 "scanner.re" */
			{
			token->opcode = PHQL_T_CAST;
			return 0;
		}
/* #line 1231 "scanner.c" */
yy149:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy150;
			if (yych != 'g') goto yy101;
yy150:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy151;
			if (yych != 'h') goto yy101;
yy151:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy152;
			if (yych != 't') goto yy101;
yy152:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy153;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy153;
					if (yych <= 'z') goto yy100;
				}
			}
yy153:
/* #line 239 "scanner.re" */
			{
			token->opcode = PHQL_T_RIGHT;
			return 0;
		}
/* #line 1268 "scanner.c" */
yy154:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy155;
			if (yych != 'i') goto yy101;
yy155:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy156;
			if (yych != 'n') goto yy101;
yy156:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy157;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy157;
					if (yych <= 'z') goto yy100;
				}
			}
yy157:
/* #line 224 "scanner.re" */
			{
			token->opcode = PHQL_T_JOIN;
			return 0;
		}
/* #line 1301 "scanner.c" */
yy158:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy163;
			if (yych == 't') goto yy163;
			goto yy101;
yy159:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy160;
			if (yych != 'l') goto yy101;
yy160:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy161;
			if (yych != 'l') goto yy101;
yy161:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy162;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy162;
					if (yych <= 'z') goto yy100;
				}
			}
yy162:
/* #line 264 "scanner.re" */
			{
			token->opcode = PHQL_T_NULL;
			return 0;
		}
/* #line 1339 "scanner.c" */
yy163:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy164;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy164;
					if (yych <= 'z') goto yy100;
				}
			}
yy164:
/* #line 184 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 1364 "scanner.c" */
yy165:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy174;
			if (yych == 'f') goto yy174;
			goto yy101;
yy166:
			yych = *++YYCURSOR;
			if (yych <= 'M') {
				if (yych == 'K') goto yy168;
				if (yych <= 'L') goto yy101;
			} else {
				if (yych <= 'k') {
					if (yych <= 'j') goto yy101;
					goto yy168;
				} else {
					if (yych != 'm') goto yy101;
				}
			}
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy171;
			if (yych == 'i') goto yy171;
			goto yy101;
yy168:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy169;
			if (yych != 'e') goto yy101;
yy169:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy170;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy170;
					if (yych <= 'z') goto yy100;
				}
			}
yy170:
/* #line 199 "scanner.re" */
			{
			token->opcode = PHQL_T_LIKE;
			return 0;
		}
/* #line 1415 "scanner.c" */
yy171:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy172;
			if (yych != 't') goto yy101;
yy172:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy173;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy173;
					if (yych <= 'z') goto yy100;
				}
			}
yy173:
/* #line 174 "scanner.re" */
			{
			token->opcode = PHQL_T_LIMIT;
			return 0;
		}
/* #line 1444 "scanner.c" */
yy174:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy175;
			if (yych != 't') goto yy101;
yy175:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy176;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy176;
					if (yych <= 'z') goto yy100;
				}
			}
yy176:
/* #line 234 "scanner.re" */
			{
			token->opcode = PHQL_T_LEFT;
			return 0;
		}
/* #line 1473 "scanner.c" */
yy177:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy178;
			if (yych != 'v') goto yy101;
yy178:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy179;
			if (yych != 'i') goto yy101;
yy179:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy180;
			if (yych != 'n') goto yy101;
yy180:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy181;
			if (yych != 'g') goto yy101;
yy181:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy182;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy182;
					if (yych <= 'z') goto yy100;
				}
			}
yy182:
/* #line 169 "scanner.re" */
			{
			token->opcode = PHQL_T_HAVING;
			return 0;
		}
/* #line 1514 "scanner.c" */
yy183:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy184;
			if (yych != 'o') goto yy101;
yy184:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy185;
			if (yych != 'u') goto yy101;
yy185:
			yych = *++YYCURSOR;
			if (yych == 'P') goto yy186;
			if (yych != 'p') goto yy101;
yy186:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy187;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy187;
					if (yych <= 'z') goto yy100;
				}
			}
yy187:
/* #line 164 "scanner.re" */
			{
			token->opcode = PHQL_T_GROUP;
			return 0;
		}
/* #line 1551 "scanner.c" */
yy188:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy191;
			if (yych == 't') goto yy191;
			goto yy101;
yy189:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy190;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy190;
					if (yych <= 'z') goto yy100;
				}
			}
yy190:
/* #line 149 "scanner.re" */
			{
			token->opcode = PHQL_T_BY;
			return 0;
		}
/* #line 1581 "scanner.c" */
yy191:
			yych = *++YYCURSOR;
			if (yych == 'W') goto yy192;
			if (yych != 'w') goto yy101;
yy192:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy193;
			if (yych != 'e') goto yy101;
yy193:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy194;
			if (yych != 'e') goto yy101;
yy194:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy195;
			if (yych != 'n') goto yy101;
yy195:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy196;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy196;
					if (yych <= 'z') goto yy100;
				}
			}
yy196:
/* #line 279 "scanner.re" */
			{
			token->opcode = PHQL_T_BETWEEN;
			return 0;
		}
/* #line 1622 "scanner.c" */
yy197:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy211;
			if (yych == 'f') goto yy211;
			goto yy101;
yy198:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy199;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy199;
					if (yych <= 'z') goto yy100;
				}
			}
yy199:
/* #line 219 "scanner.re" */
			{
			token->opcode = PHQL_T_ON;
			return 0;
		}
/* #line 1652 "scanner.c" */
yy200:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy201;
					if (yych <= ':') goto yy100;
				} else {
					if (yych == 'D') goto yy207;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy100;
					if (yych == '_') goto yy100;
				} else {
					if (yych == 'd') goto yy207;
					if (yych <= 'z') goto yy100;
				}
			}
yy201:
/* #line 194 "scanner.re" */
			{
			token->opcode = PHQL_T_OR;
			return 0;
		}
/* #line 1678 "scanner.c" */
yy202:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy203;
			if (yych != 't') goto yy101;
yy203:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy204;
			if (yych != 'e') goto yy101;
yy204:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy205;
			if (yych != 'r') goto yy101;
yy205:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy206;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy206;
					if (yych <= 'z') goto yy100;
				}
			}
yy206:
/* #line 249 "scanner.re" */
			{
			token->opcode = PHQL_T_OUTER;
			return 0;
		}
/* #line 1715 "scanner.c" */
yy207:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy208;
			if (yych != 'e') goto yy101;
yy208:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy209;
			if (yych != 'r') goto yy101;
yy209:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy210;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy210;
					if (yych <= 'z') goto yy100;
				}
			}
yy210:
/* #line 144 "scanner.re" */
			{
			token->opcode = PHQL_T_ORDER;
			return 0;
		}
/* #line 1748 "scanner.c" */
yy211:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy212;
			if (yych != 's') goto yy101;
yy212:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy213;
			if (yych != 'e') goto yy101;
yy213:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy214;
			if (yych != 't') goto yy101;
yy214:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy215;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy215;
					if (yych <= 'z') goto yy100;
				}
			}
yy215:
/* #line 179 "scanner.re" */
			{
			token->opcode = PHQL_T_OFFSET;
			return 0;
		}
/* #line 1785 "scanner.c" */
yy216:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy217;
			if (yych != 'e') goto yy101;
yy217:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'N') goto yy218;
				if (yych <= 'Q') goto yy101;
				goto yy220;
			} else {
				if (yych <= 'n') {
					if (yych <= 'm') goto yy101;
				} else {
					if (yych == 'r') goto yy220;
					goto yy101;
				}
			}
yy218:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy219;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy219;
					if (yych <= 'z') goto yy100;
				}
			}
yy219:
/* #line 324 "scanner.re" */
			{
			token->opcode = PHQL_T_WHEN;
			return 0;
		}
/* #line 1828 "scanner.c" */
yy220:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy221;
			if (yych != 'e') goto yy101;
yy221:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy222;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy222;
					if (yych <= 'z') goto yy100;
				}
			}
yy222:
/* #line 134 "scanner.re" */
			{
			token->opcode = PHQL_T_WHERE;
			return 0;
		}
/* #line 1857 "scanner.c" */
yy223:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy224;
			if (yych != 'l') goto yy101;
yy224:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy225;
			if (yych != 'u') goto yy101;
yy225:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy226;
			if (yych != 'e') goto yy101;
yy226:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy227;
			if (yych != 's') goto yy101;
yy227:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy228;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy228;
					if (yych <= 'z') goto yy100;
				}
			}
yy228:
/* #line 129 "scanner.re" */
			{
			token->opcode = PHQL_T_VALUES;
			return 0;
		}
/* #line 1898 "scanner.c" */
yy229:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy246;
			if (yych == 'i') goto yy246;
			goto yy101;
yy230:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= 'N') {
					if (yych <= ':') {
						if (yych >= '0') goto yy100;
					} else {
						if (yych <= '@') goto yy231;
						if (yych <= 'M') goto yy100;
						goto yy236;
					}
				} else {
					if (yych <= 'S') {
						if (yych <= 'R') goto yy100;
						goto yy234;
					} else {
						if (yych <= 'T') goto yy235;
						if (yych <= 'Z') goto yy100;
					}
				}
			} else {
				if (yych <= 'm') {
					if (yych <= '^') {
						if (yych <= '\\') goto yy100;
					} else {
						if (yych != '`') goto yy100;
					}
				} else {
					if (yych <= 's') {
						if (yych <= 'n') goto yy236;
						if (yych <= 'r') goto yy100;
						goto yy234;
					} else {
						if (yych <= 't') goto yy235;
						if (yych <= 'z') goto yy100;
					}
				}
			}
yy231:
/* #line 214 "scanner.re" */
			{
			token->opcode = PHQL_T_IN;
			return 0;
		}
/* #line 1948 "scanner.c" */
yy232:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy233;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy233;
					if (yych <= 'z') goto yy100;
				}
			}
yy233:
/* #line 259 "scanner.re" */
			{
			token->opcode = PHQL_T_IS;
			return 0;
		}
/* #line 1973 "scanner.c" */
yy234:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy242;
			if (yych == 'e') goto yy242;
			goto yy101;
yy235:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy240;
			if (yych == 'o') goto yy240;
			goto yy101;
yy236:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy237;
			if (yych != 'e') goto yy101;
yy237:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy238;
			if (yych != 'r') goto yy101;
yy238:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy239;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy239;
					if (yych <= 'z') goto yy100;
				}
			}
yy239:
/* #line 229 "scanner.re" */
			{
			token->opcode = PHQL_T_INNER;
			return 0;
		}
/* #line 2016 "scanner.c" */
yy240:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy241;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy241;
					if (yych <= 'z') goto yy100;
				}
			}
yy241:
/* #line 124 "scanner.re" */
			{
			token->opcode = PHQL_T_INTO;
			return 0;
		}
/* #line 2041 "scanner.c" */
yy242:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy243;
			if (yych != 'r') goto yy101;
yy243:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy244;
			if (yych != 't') goto yy101;
yy244:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy245;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy245;
					if (yych <= 'z') goto yy100;
				}
			}
yy245:
/* #line 119 "scanner.re" */
			{
			token->opcode = PHQL_T_INSERT;
			return 0;
		}
/* #line 2074 "scanner.c" */
yy246:
			yych = *++YYCURSOR;
			if (yych == 'K') goto yy247;
			if (yych != 'k') goto yy101;
yy247:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy248;
			if (yych != 'e') goto yy101;
yy248:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy249;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy249;
					if (yych <= 'z') goto yy100;
				}
			}
yy249:
/* #line 204 "scanner.re" */
			{
			token->opcode = PHQL_T_ILIKE;
			return 0;
		}
/* #line 2107 "scanner.c" */
yy250:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy261;
			if (yych == 'a') goto yy261;
			goto yy101;
yy251:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy259;
			if (yych == 'l') goto yy259;
			goto yy101;
yy252:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy257;
			if (yych == 'd') goto yy257;
			goto yy101;
yy253:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy254;
					if (yych <= ':') goto yy100;
				} else {
					if (yych == 'C') goto yy255;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy100;
					if (yych == '_') goto yy100;
				} else {
					if (yych == 'c') goto yy255;
					if (yych <= 'z') goto yy100;
				}
			}
yy254:
/* #line 114 "scanner.re" */
			{
			token->opcode = PHQL_T_AS;
			return 0;
		}
/* #line 2148 "scanner.c" */
yy255:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy256;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy256;
					if (yych <= 'z') goto yy100;
				}
			}
yy256:
/* #line 154 "scanner.re" */
			{
			token->opcode = PHQL_T_ASC;
			return 0;
		}
/* #line 2173 "scanner.c" */
yy257:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy258;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy258;
					if (yych <= 'z') goto yy100;
				}
			}
yy258:
/* #line 189 "scanner.re" */
			{
			token->opcode = PHQL_T_AND;
			return 0;
		}
/* #line 2198 "scanner.c" */
yy259:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy260;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy260;
					if (yych <= 'z') goto yy100;
				}
			}
yy260:
/* #line 274 "scanner.re" */
			{
			token->opcode = PHQL_T_ALL;
			return 0;
		}
/* #line 2223 "scanner.c" */
yy261:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy262;
			if (yych != 'i') goto yy101;
yy262:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy263;
			if (yych != 'n') goto yy101;
yy263:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy264;
			if (yych != 's') goto yy101;
yy264:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy265;
			if (yych != 't') goto yy101;
yy265:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy266;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy266;
					if (yych <= 'z') goto yy100;
				}
			}
yy266:
/* #line 209 "scanner.re" */
			{
			token->opcode = PHQL_T_AGAINST;
			return 0;
		}
/* #line 2264 "scanner.c" */
yy267:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy279;
			if (yych == 'l') goto yy279;
			goto yy101;
yy268:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy277;
			if (yych == 'r') goto yy277;
			goto yy101;
yy269:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy274;
			if (yych == 'o') goto yy274;
			goto yy101;
yy270:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy271;
			if (yych != 'l') goto yy101;
yy271:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy272;
			if (yych != 'l') goto yy101;
yy272:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy273;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy273;
					if (yych <= 'z') goto yy100;
				}
			}
yy273:
/* #line 254 "scanner.re" */
			{
			token->opcode = PHQL_T_FULL;
			return 0;
		}
/* #line 2312 "scanner.c" */
yy274:
			yych = *++YYCURSOR;
			if (yych == 'M') goto yy275;
			if (yych != 'm') goto yy101;
yy275:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy276;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy276;
					if (yych <= 'z') goto yy100;
				}
			}
yy276:
/* #line 109 "scanner.re" */
			{
			token->opcode = PHQL_T_FROM;
			return 0;
		}
/* #line 2341 "scanner.c" */
yy277:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy278;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy278;
					if (yych <= 'z') goto yy100;
				}
			}
yy278:
/* #line 314 "scanner.re" */
			{
			token->opcode = PHQL_T_FOR;
			return 0;
		}
/* #line 2366 "scanner.c" */
yy279:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy280;
			if (yych != 's') goto yy101;
yy280:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy281;
			if (yych != 'e') goto yy101;
yy281:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy282;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy282;
					if (yych <= 'z') goto yy100;
				}
			}
yy282:
/* #line 309 "scanner.re" */
			{
			token->opcode = PHQL_T_FALSE;
			return 0;
		}
/* #line 2399 "scanner.c" */
yy283:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych == 'L') goto yy292;
				if (yych <= 'R') goto yy101;
				goto yy293;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy101;
					goto yy292;
				} else {
					if (yych == 's') goto yy293;
					goto yy101;
				}
			}
yy284:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy285;
			if (yych != 's') goto yy101;
yy285:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy286;
			if (yych != 't') goto yy101;
yy286:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy287;
			if (yych != 'i') goto yy101;
yy287:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy288;
			if (yych != 'n') goto yy101;
yy288:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy289;
			if (yych != 'c') goto yy101;
yy289:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy290;
			if (yych != 't') goto yy101;
yy290:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy291;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy291;
					if (yych <= 'z') goto yy100;
				}
			}
yy291:
/* #line 269 "scanner.re" */
			{
			token->opcode = PHQL_T_DISTINCT;
			return 0;
		}
/* #line 2463 "scanner.c" */
yy292:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy296;
			if (yych == 'e') goto yy296;
			goto yy101;
yy293:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy294;
			if (yych != 'c') goto yy101;
yy294:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy295;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy295;
					if (yych <= 'z') goto yy100;
				}
			}
yy295:
/* #line 159 "scanner.re" */
			{
			token->opcode = PHQL_T_DESC;
			return 0;
		}
/* #line 2497 "scanner.c" */
yy296:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy297;
			if (yych != 't') goto yy101;
yy297:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy298;
			if (yych != 'e') goto yy101;
yy298:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy299;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy299;
					if (yych <= 'z') goto yy100;
				}
			}
yy299:
/* #line 104 "scanner.re" */
			{
			token->opcode = PHQL_T_DELETE;
			return 0;
		}
/* #line 2530 "scanner.c" */
yy300:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'L') goto yy303;
				if (yych <= 'S') goto yy101;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy101;
					goto yy303;
				} else {
					if (yych != 't') goto yy101;
				}
			}
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy302;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy302;
					if (yych <= 'z') goto yy100;
				}
			}
yy302:
/* #line 99 "scanner.re" */
			{
			token->opcode = PHQL_T_SET;
			return 0;
		}
/* #line 2567 "scanner.c" */
yy303:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy304;
			if (yych != 'e') goto yy101;
yy304:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy305;
			if (yych != 'c') goto yy101;
yy305:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy306;
			if (yych != 't') goto yy101;
yy306:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy307;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy307;
					if (yych <= 'z') goto yy100;
				}
			}
yy307:
/* #line 139 "scanner.re" */
			{
			token->opcode = PHQL_T_SELECT;
			return 0;
		}
/* #line 2604 "scanner.c" */
yy308:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy314;
			if (yych == 'd') goto yy314;
			goto yy101;
yy309:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy310;
			if (yych != 'i') goto yy101;
yy310:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy311;
			if (yych != 'n') goto yy101;
yy311:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy312;
			if (yych != 'g') goto yy101;
yy312:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy313;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy313;
					if (yych <= 'z') goto yy100;
				}
			}
yy313:
/* #line 294 "scanner.re" */
			{
			token->opcode = PHQL_T_USING;
			return 0;
		}
/* #line 2646 "scanner.c" */
yy314:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy315;
			if (yych != 'a') goto yy101;
yy315:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy316;
			if (yych != 't') goto yy101;
yy316:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy317;
			if (yych != 'e') goto yy101;
yy317:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= ':') {
					if (yych >= '0') goto yy100;
				} else {
					if (yych <= '@') goto yy318;
					if (yych <= 'Z') goto yy100;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy100;
					if (yych >= '_') goto yy100;
				} else {
					if (yych <= '`') goto yy318;
					if (yych <= 'z') goto yy100;
				}
			}
yy318:
/* #line 94 "scanner.re" */
			{
			token->opcode = PHQL_T_UPDATE;
			return 0;
		}
/* #line 2683 "scanner.c" */
yy319:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 16) {
				goto yy319;
			}
			if (yych != '}') goto yy97;
			++YYCURSOR;
/* #line 86 "scanner.re" */
			{
			token->opcode = PHQL_T_BPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 2700 "scanner.c" */
yy323:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 32) {
				goto yy323;
			}
			if (yych != ':') goto yy97;
			++YYCURSOR;
/* #line 77 "scanner.re" */
			{
			token->opcode = PHQL_T_SPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 2717 "scanner.c" */
yy327:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 64) {
				goto yy327;
			}
/* #line 68 "scanner.re" */
			{
			token->opcode = PHQL_T_NPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 2732 "scanner.c" */
yy330:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy332;
			if (yych <= '9') goto yy330;
yy332:
/* #line 59 "scanner.re" */
			{
			token->opcode = PHQL_T_DOUBLE;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 2747 "scanner.c" */
yy333:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy332;
			if (yych <= '9') goto yy333;
			goto yy332;
yy335:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '.') goto yy333;
			if (yych <= '/') goto yy3;
			if (yych <= '9') goto yy335;
			goto yy3;
yy337:
			yych = *++YYCURSOR;
			if (yybm[0+yych] & 128) {
				goto yy338;
			}
			goto yy97;
yy338:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 128) {
				goto yy338;
			}
/* #line 41 "scanner.re" */
			{
			token->opcode = PHQL_T_HINTEGER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 2781 "scanner.c" */
		}
/* #line 536 "scanner.re" */

	}

	return status;
}
