/* Generated by re2c 0.16 on Sat Jul  1 09:12:16 2017 */
/* #line 1 "scanner.re" */

/*
  +------------------------------------------------------------------------+
  | Phalcon Framework                                                      |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2016 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  +------------------------------------------------------------------------+
*/

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include "php_phalcon.h"

#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int phql_get_token(phql_scanner_state *s, phql_scanner_token *token) {

	char *q = YYCURSOR;
	int status = PHQL_SCANNER_RETCODE_IMPOSSIBLE;

	while (PHQL_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
/* #line 45 "scanner.c" */
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;
			static const unsigned char yybm[] = {
				  0,  48,  48,  48,  48,  48,  48,  48, 
				 48,  49,  49,  48,  48,  49,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 49,  48,  32,  48,  48,  48,  48,  16, 
				 48,  48,  48,  48,  48, 240,  48,  48, 
				254, 254, 254, 254, 254, 254, 254, 254, 
				254, 254, 180,  48,  48,  48,  48,  48, 
				 48, 252, 252, 252, 252, 252, 252, 244, 
				244, 244, 244, 244, 244, 244, 244, 244, 
				244, 244, 244, 244, 244, 244, 244, 244, 
				244, 244, 244,  48,   4,  48,  48, 244, 
				 48, 252, 252, 252, 252, 252, 252, 244, 
				244, 244, 244, 244, 244, 244, 244, 244, 
				244, 244, 244, 244, 244, 244, 244, 244, 
				252, 244, 244,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
			};
			yych = *YYCURSOR;
			if (yybm[0+yych] & 1) {
				goto yy6;
			}
			switch (yych) {
			case 0x00:	goto yy2;
			case ' ':
			case '!':	goto yy9;
			case '"':	goto yy11;
			case '%':	goto yy12;
			case '&':	goto yy14;
			case '\'':	goto yy16;
			case '(':	goto yy17;
			case ')':	goto yy19;
			case '*':	goto yy21;
			case '+':	goto yy23;
			case ',':	goto yy25;
			case '-':	goto yy27;
			case '.':	goto yy29;
			case '/':	goto yy31;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy33;
			case ':':	goto yy36;
			case '<':	goto yy38;
			case '=':	goto yy40;
			case '>':	goto yy42;
			case '?':	goto yy44;
			case '@':	goto yy45;
			case 'A':
			case 'a':	goto yy46;
			case 'B':
			case 'b':	goto yy47;
			case 'C':
			case 'c':	goto yy48;
			case 'D':
			case 'd':	goto yy49;
			case 'E':
			case 'e':	goto yy50;
			case 'F':
			case 'f':	goto yy51;
			case 'G':
			case 'g':	goto yy52;
			case 'H':
			case 'h':	goto yy54;
			case 'I':
			case 'i':	goto yy55;
			case 'J':
			case 'j':	goto yy56;
			case 'K':
			case 'M':
			case 'P':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'k':
			case 'm':
			case 'p':
			case 'q':
			case 'y':
			case 'z':	goto yy57;
			case 'L':
			case 'l':	goto yy59;
			case 'N':
			case 'n':	goto yy60;
			case 'O':
			case 'o':	goto yy61;
			case 'R':
			case 'r':	goto yy62;
			case 'S':
			case 's':	goto yy63;
			case 'T':
			case 't':	goto yy64;
			case 'U':
			case 'u':	goto yy65;
			case 'V':
			case 'v':	goto yy66;
			case 'W':
			case 'w':	goto yy67;
			case '[':	goto yy68;
			case '\\':	goto yy69;
			case '^':	goto yy70;
			case 'x':	goto yy72;
			case '{':	goto yy74;
			case '|':	goto yy75;
			case '~':	goto yy77;
			default:	goto yy4;
			}
yy2:
			++YYCURSOR;
/* #line 577 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_EOF;
			break;
		}
/* #line 187 "scanner.c" */
yy4:
			++YYCURSOR;
yy5:
/* #line 582 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_ERR;
			break;
		}
/* #line 196 "scanner.c" */
yy6:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 1) {
				goto yy6;
			}
/* #line 572 "scanner.re" */
			{
			token->opcode = PHQL_T_IGNORE;
			return 0;
		}
/* #line 208 "scanner.c" */
yy9:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '!') goto yy79;
			if (yych == '=') goto yy81;
/* #line 547 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 218 "scanner.c" */
yy11:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy5;
			goto yy84;
yy12:
			++YYCURSOR;
/* #line 447 "scanner.re" */
			{
			token->opcode = PHQL_T_MOD;
			return 0;
		}
/* #line 231 "scanner.c" */
yy14:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '&') goto yy89;
/* #line 562 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_AND;
			return 0;
		}
/* #line 240 "scanner.c" */
yy16:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy5;
			goto yy92;
yy17:
			++YYCURSOR;
/* #line 472 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_OPEN;
			return 0;
		}
/* #line 253 "scanner.c" */
yy19:
			++YYCURSOR;
/* #line 477 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_CLOSE;
			return 0;
		}
/* #line 261 "scanner.c" */
yy21:
			++YYCURSOR;
/* #line 437 "scanner.re" */
			{
			token->opcode = PHQL_T_MUL;
			return 0;
		}
/* #line 269 "scanner.c" */
yy23:
			++YYCURSOR;
/* #line 427 "scanner.re" */
			{
			token->opcode = PHQL_T_ADD;
			return 0;
		}
/* #line 277 "scanner.c" */
yy25:
			++YYCURSOR;
/* #line 467 "scanner.re" */
			{
			token->opcode = PHQL_T_COMMA;
			return 0;
		}
/* #line 285 "scanner.c" */
yy27:
			++YYCURSOR;
/* #line 432 "scanner.re" */
			{
			token->opcode = PHQL_T_SUB;
			return 0;
		}
/* #line 293 "scanner.c" */
yy29:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '/') goto yy30;
			if (yych <= '9') goto yy94;
yy30:
/* #line 452 "scanner.re" */
			{
			token->opcode = PHQL_T_DOT;
			return 0;
		}
/* #line 304 "scanner.c" */
yy31:
			++YYCURSOR;
/* #line 442 "scanner.re" */
			{
			token->opcode = PHQL_T_DIV;
			return 0;
		}
/* #line 312 "scanner.c" */
yy33:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 2) {
				goto yy33;
			}
			if (yych <= 'F') {
				if (yych == '.') goto yy94;
				if (yych >= 'A') goto yy97;
			} else {
				if (yych <= 'f') {
					if (yych >= 'a') goto yy97;
				} else {
					if (yych == 'x') goto yy97;
				}
			}
yy35:
/* #line 46 "scanner.re" */
			{
            token->value = estrndup(q, YYCURSOR - q);
            token->len = YYCURSOR - q;
            if (token->len > 2 && !memcmp(token->value, "0x", 2)) {
			    token->opcode = PHQL_T_HINTEGER;
            } else {
                int i, alpha = 0;
                for (i = 0; i < token->len; i++) {
                    unsigned char ch = token->value[i];
                    if (!((ch >= '0') && (ch <= '9'))) {
                        alpha = 1;
                        break;
                    }
                }
                if (alpha) {
                    token->opcode = PHQL_T_IDENTIFIER;
                } else {
                    token->opcode = PHQL_T_INTEGER;
                }
            }
			q = YYCURSOR;
			return 0;
		}
/* #line 354 "scanner.c" */
yy36:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 64) {
				goto yy99;
			}
			if (yych <= '/') goto yy37;
			if (yych <= ':') goto yy101;
yy37:
/* #line 462 "scanner.re" */
			{
			token->opcode = PHQL_T_COLON;
			return 0;
		}
/* #line 369 "scanner.c" */
yy38:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '<') goto yy39;
			if (yych <= '=') goto yy103;
			if (yych <= '>') goto yy105;
yy39:
/* #line 502 "scanner.re" */
			{
			token->opcode = PHQL_T_LESS;
			return 0;
		}
/* #line 381 "scanner.c" */
yy40:
			++YYCURSOR;
/* #line 512 "scanner.re" */
			{
			token->opcode = PHQL_T_EQUALS;
			return 0;
		}
/* #line 389 "scanner.c" */
yy42:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '=') goto yy107;
/* #line 507 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATER;
			return 0;
		}
/* #line 398 "scanner.c" */
yy44:
			yych = *++YYCURSOR;
			if (yych <= '/') goto yy5;
			if (yych <= '9') goto yy109;
			goto yy5;
yy45:
			yych = *++YYCURSOR;
			if (yych == '>') goto yy112;
			if (yych == '@') goto yy114;
			goto yy5;
yy46:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy116;
			case 'L':
			case 'l':	goto yy117;
			case 'N':
			case 'n':	goto yy118;
			case 'S':
			case 's':	goto yy119;
			default:	goto yy73;
			}
yy47:
			yych = *++YYCURSOR;
			if (yych <= 'Y') {
				if (yych == 'E') goto yy121;
				if (yych <= 'X') goto yy73;
				goto yy122;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy73;
					goto yy121;
				} else {
					if (yych == 'y') goto yy122;
					goto yy73;
				}
			}
yy48:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych <= 'N') {
					if (yych == 'A') goto yy124;
					goto yy73;
				} else {
					if (yych <= 'O') goto yy125;
					if (yych <= 'Q') goto yy73;
					goto yy126;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'a') goto yy124;
					goto yy73;
				} else {
					if (yych <= 'o') goto yy125;
					if (yych == 'r') goto yy126;
					goto yy73;
				}
			}
yy49:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy127;
				if (yych <= 'H') goto yy73;
				goto yy128;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy73;
					goto yy127;
				} else {
					if (yych == 'i') goto yy128;
					goto yy73;
				}
			}
yy50:
			yych = *++YYCURSOR;
			if (yych <= 'X') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy129;
					goto yy73;
				} else {
					if (yych <= 'N') goto yy130;
					if (yych <= 'W') goto yy73;
					goto yy131;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy129;
					goto yy73;
				} else {
					if (yych <= 'n') goto yy130;
					if (yych == 'x') goto yy132;
					goto yy73;
				}
			}
yy51:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'O') {
					if (yych == 'A') goto yy133;
					if (yych <= 'N') goto yy73;
					goto yy134;
				} else {
					if (yych == 'R') goto yy135;
					if (yych <= 'T') goto yy73;
					goto yy136;
				}
			} else {
				if (yych <= 'o') {
					if (yych == 'a') goto yy133;
					if (yych <= 'n') goto yy73;
					goto yy134;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy73;
						goto yy135;
					} else {
						if (yych == 'u') goto yy136;
						goto yy73;
					}
				}
			}
yy52:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == 'R') goto yy137;
			if (yych == 'r') goto yy137;
			goto yy58;
yy53:
/* #line 400 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			if ((YYCURSOR - q) > 1) {
				if (q[0] == '\\') {
					token->value = estrndup(q + 1, YYCURSOR - q - 1);
					token->len = YYCURSOR - q - 1;
				} else {
					token->value = estrndup(q, YYCURSOR - q);
					token->len = YYCURSOR - q;
				}
			} else {
				token->value = estrndup(q, YYCURSOR - q);
				token->len = YYCURSOR - q;
			}
			q = YYCURSOR;
			return 0;
		}
/* #line 545 "scanner.c" */
yy54:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy138;
			if (yych == 'a') goto yy138;
			goto yy58;
yy55:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy139;
			case 'L':
			case 'l':	goto yy140;
			case 'N':
			case 'n':	goto yy141;
			case 'S':
			case 's':	goto yy143;
			default:	goto yy58;
			}
yy56:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy145;
			if (yych == 'o') goto yy145;
			goto yy58;
yy57:
			++YYCURSOR;
			yych = *YYCURSOR;
yy58:
			if (yybm[0+yych] & 4) {
				goto yy57;
			}
			goto yy53;
yy59:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy146;
				if (yych <= 'H') goto yy58;
				goto yy147;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy58;
					goto yy146;
				} else {
					if (yych == 'i') goto yy147;
					goto yy58;
				}
			}
yy60:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych == 'O') goto yy148;
				if (yych <= 'T') goto yy58;
				goto yy149;
			} else {
				if (yych <= 'o') {
					if (yych <= 'n') goto yy58;
					goto yy148;
				} else {
					if (yych == 'u') goto yy149;
					goto yy58;
				}
			}
yy61:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'N') {
					if (yych == 'F') goto yy150;
					if (yych <= 'M') goto yy58;
					goto yy151;
				} else {
					if (yych == 'R') goto yy153;
					if (yych <= 'T') goto yy58;
					goto yy155;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'f') goto yy150;
					if (yych <= 'm') goto yy58;
					goto yy151;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy58;
						goto yy153;
					} else {
						if (yych == 'u') goto yy155;
						goto yy58;
					}
				}
			}
yy62:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy156;
			if (yych == 'i') goto yy156;
			goto yy58;
yy63:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy157;
			if (yych == 'e') goto yy157;
			goto yy58;
yy64:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'H') goto yy158;
				if (yych <= 'Q') goto yy58;
				goto yy159;
			} else {
				if (yych <= 'h') {
					if (yych <= 'g') goto yy58;
					goto yy158;
				} else {
					if (yych == 'r') goto yy159;
					goto yy58;
				}
			}
yy65:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych == 'P') goto yy160;
				if (yych <= 'R') goto yy58;
				goto yy161;
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy58;
					goto yy160;
				} else {
					if (yych == 's') goto yy161;
					goto yy58;
				}
			}
yy66:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy162;
			if (yych == 'a') goto yy162;
			goto yy58;
yy67:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych <= 'G') goto yy58;
				if (yych <= 'H') goto yy163;
				goto yy164;
			} else {
				if (yych <= 'g') goto yy58;
				if (yych <= 'h') goto yy163;
				if (yych <= 'i') goto yy164;
				goto yy58;
			}
yy68:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= '\\') {
				if (yych <= '@') goto yy5;
				if (yych == '[') goto yy5;
				goto yy165;
			} else {
				if (yych <= '_') {
					if (yych <= '^') goto yy5;
					goto yy165;
				} else {
					if (yych <= '`') goto yy5;
					if (yych <= 'z') goto yy165;
					goto yy5;
				}
			}
yy69:
			yych = *++YYCURSOR;
			if (yych <= '^') {
				if (yych <= '@') goto yy5;
				if (yych <= 'Z') goto yy57;
				goto yy5;
			} else {
				if (yych == '`') goto yy5;
				if (yych <= 'z') goto yy57;
				goto yy5;
			}
yy70:
			++YYCURSOR;
/* #line 557 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_XOR;
			return 0;
		}
/* #line 726 "scanner.c" */
yy72:
			++YYCURSOR;
			yych = *YYCURSOR;
yy73:
			if (yybm[0+yych] & 8) {
				goto yy72;
			}
			if (yych <= '[') {
				if (yych <= ':') {
					if (yych <= '/') goto yy35;
					goto yy57;
				} else {
					if (yych <= '@') goto yy35;
					if (yych <= 'Z') goto yy57;
					goto yy35;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy57;
					if (yych <= '^') goto yy35;
					goto yy57;
				} else {
					if (yych <= '`') goto yy35;
					if (yych <= 'z') goto yy57;
					goto yy35;
				}
			}
yy74:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 128) {
				goto yy167;
			}
			goto yy5;
yy75:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '|') goto yy169;
/* #line 567 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_OR;
			return 0;
		}
/* #line 769 "scanner.c" */
yy77:
			++YYCURSOR;
/* #line 552 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_NOT;
			return 0;
		}
/* #line 777 "scanner.c" */
yy79:
			++YYCURSOR;
/* #line 532 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_NEGATE;
			return 0;
		}
/* #line 785 "scanner.c" */
yy81:
			++YYCURSOR;
/* #line 482 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 793 "scanner.c" */
yy83:
			++YYCURSOR;
			yych = *YYCURSOR;
yy84:
			if (yybm[0+yych] & 16) {
				goto yy83;
			}
			if (yych <= 0x00) goto yy85;
			if (yych <= '"') goto yy86;
			goto yy88;
yy85:
			YYCURSOR = YYMARKER;
			if (yyaccept == 0) {
				goto yy5;
			} else {
				goto yy37;
			}
yy86:
			++YYCURSOR;
/* #line 391 "scanner.re" */
			{
			token->opcode = PHQL_T_STRING;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 821 "scanner.c" */
yy88:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy85;
			goto yy83;
yy89:
			++YYCURSOR;
/* #line 527 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_AND;
			return 0;
		}
/* #line 834 "scanner.c" */
yy91:
			++YYCURSOR;
			yych = *YYCURSOR;
yy92:
			if (yybm[0+yych] & 32) {
				goto yy91;
			}
			if (yych <= 0x00) goto yy85;
			if (yych <= '\'') goto yy86;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy85;
			goto yy91;
yy94:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy96;
			if (yych <= '9') goto yy94;
yy96:
/* #line 80 "scanner.re" */
			{
			token->opcode = PHQL_T_DOUBLE;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 862 "scanner.c" */
yy97:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= 'F') {
				if (yych <= '/') goto yy35;
				if (yych <= '9') goto yy97;
				if (yych <= '@') goto yy35;
				goto yy97;
			} else {
				if (yych <= 'f') {
					if (yych <= '`') goto yy35;
					goto yy97;
				} else {
					if (yych == 'x') goto yy97;
					goto yy35;
				}
			}
yy99:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 64) {
				goto yy99;
			}
			if (yych <= '/') goto yy85;
			if (yych <= ':') goto yy171;
			goto yy85;
yy101:
			++YYCURSOR;
/* #line 457 "scanner.re" */
			{
			token->opcode = PHQL_T_DOUBLECOLON;
			return 0;
		}
/* #line 896 "scanner.c" */
yy103:
			++YYCURSOR;
/* #line 492 "scanner.re" */
			{
			token->opcode = PHQL_T_LESSEQUAL;
			return 0;
		}
/* #line 904 "scanner.c" */
yy105:
			++YYCURSOR;
/* #line 487 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 912 "scanner.c" */
yy107:
			++YYCURSOR;
/* #line 497 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATEREQUAL;
			return 0;
		}
/* #line 920 "scanner.c" */
yy109:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy111;
			if (yych <= '9') goto yy109;
yy111:
/* #line 89 "scanner.re" */
			{
			token->opcode = PHQL_T_NPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 935 "scanner.c" */
yy112:
			++YYCURSOR;
/* #line 537 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_CONTAINS_ANOTHER;
			return 0;
		}
/* #line 943 "scanner.c" */
yy114:
			++YYCURSOR;
/* #line 517 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_MATCHES;
			return 0;
		}
/* #line 951 "scanner.c" */
yy116:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy173;
			if (yych == 'a') goto yy173;
			goto yy58;
yy117:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy174;
			if (yych == 'l') goto yy174;
			goto yy58;
yy118:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy176;
			if (yych == 'd') goto yy176;
			goto yy58;
yy119:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy120;
					if (yych <= ':') goto yy57;
				} else {
					if (yych == 'C') goto yy178;
					if (yych <= 'Z') goto yy57;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy57;
					if (yych == '_') goto yy57;
				} else {
					if (yych == 'c') goto yy178;
					if (yych <= 'z') goto yy57;
				}
			}
yy120:
/* #line 135 "scanner.re" */
			{
			token->opcode = PHQL_T_AS;
			return 0;
		}
/* #line 992 "scanner.c" */
yy121:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy180;
			if (yych == 't') goto yy180;
			goto yy73;
yy122:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 170 "scanner.re" */
			{
			token->opcode = PHQL_T_BY;
			return 0;
		}
/* #line 1008 "scanner.c" */
yy124:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy181;
			if (yych == 's') goto yy181;
			goto yy73;
yy125:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy182;
			if (yych == 'n') goto yy182;
			goto yy58;
yy126:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy183;
			if (yych == 'o') goto yy183;
			goto yy58;
yy127:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych == 'L') goto yy184;
				if (yych <= 'R') goto yy73;
				goto yy185;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy73;
					goto yy184;
				} else {
					if (yych == 's') goto yy185;
					goto yy73;
				}
			}
yy128:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy186;
			if (yych == 's') goto yy186;
			goto yy58;
yy129:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy187;
			if (yych == 's') goto yy187;
			goto yy58;
yy130:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy188;
			if (yych == 'd') goto yy188;
			goto yy58;
yy131:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy190;
			if (yych == 'i') goto yy190;
			goto yy58;
yy132:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy190;
			if (yych == 'i') goto yy190;
			goto yy73;
yy133:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy191;
			if (yych == 'l') goto yy191;
			goto yy73;
yy134:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy192;
			if (yych == 'r') goto yy192;
			goto yy58;
yy135:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy194;
			if (yych == 'o') goto yy194;
			goto yy58;
yy136:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy195;
			if (yych == 'l') goto yy195;
			goto yy58;
yy137:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy196;
			if (yych == 'o') goto yy196;
			goto yy58;
yy138:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy197;
			if (yych == 'v') goto yy197;
			goto yy58;
yy139:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy198;
			if (yych == 'n') goto yy198;
			goto yy58;
yy140:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy199;
			if (yych == 'i') goto yy199;
			goto yy58;
yy141:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= 'M') {
					if (yych <= '@') {
						if (yych <= '/') goto yy142;
						if (yych <= ':') goto yy57;
					} else {
						if (yych == 'D') goto yy200;
						goto yy57;
					}
				} else {
					if (yych <= 'S') {
						if (yych <= 'N') goto yy201;
						if (yych <= 'R') goto yy57;
						goto yy202;
					} else {
						if (yych <= 'T') goto yy203;
						if (yych <= 'Z') goto yy57;
					}
				}
			} else {
				if (yych <= 'd') {
					if (yych <= '_') {
						if (yych <= '\\') goto yy57;
						if (yych >= '_') goto yy57;
					} else {
						if (yych <= '`') goto yy142;
						if (yych <= 'c') goto yy57;
						goto yy200;
					}
				} else {
					if (yych <= 'r') {
						if (yych == 'n') goto yy201;
						goto yy57;
					} else {
						if (yych <= 's') goto yy202;
						if (yych <= 't') goto yy203;
						if (yych <= 'z') goto yy57;
					}
				}
			}
yy142:
/* #line 235 "scanner.re" */
			{
			token->opcode = PHQL_T_IN;
			return 0;
		}
/* #line 1152 "scanner.c" */
yy143:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 280 "scanner.re" */
			{
			token->opcode = PHQL_T_IS;
			return 0;
		}
/* #line 1163 "scanner.c" */
yy145:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy204;
			if (yych == 'i') goto yy204;
			goto yy58;
yy146:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy205;
			if (yych == 'f') goto yy205;
			goto yy58;
yy147:
			yych = *++YYCURSOR;
			if (yych <= 'M') {
				if (yych == 'K') goto yy206;
				if (yych <= 'L') goto yy58;
				goto yy207;
			} else {
				if (yych <= 'k') {
					if (yych <= 'j') goto yy58;
					goto yy206;
				} else {
					if (yych == 'm') goto yy207;
					goto yy58;
				}
			}
yy148:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy208;
			if (yych == 't') goto yy208;
			goto yy58;
yy149:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy210;
			if (yych == 'l') goto yy210;
			goto yy58;
yy150:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy211;
			if (yych == 'f') goto yy211;
			goto yy58;
yy151:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 240 "scanner.re" */
			{
			token->opcode = PHQL_T_ON;
			return 0;
		}
/* #line 1214 "scanner.c" */
yy153:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy154;
					if (yych <= ':') goto yy57;
				} else {
					if (yych == 'D') goto yy212;
					if (yych <= 'Z') goto yy57;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy57;
					if (yych == '_') goto yy57;
				} else {
					if (yych == 'd') goto yy212;
					if (yych <= 'z') goto yy57;
				}
			}
yy154:
/* #line 215 "scanner.re" */
			{
			token->opcode = PHQL_T_OR;
			return 0;
		}
/* #line 1240 "scanner.c" */
yy155:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy213;
			if (yych == 't') goto yy213;
			goto yy58;
yy156:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy214;
			if (yych == 'g') goto yy214;
			goto yy58;
yy157:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'L') goto yy215;
				if (yych <= 'S') goto yy58;
				goto yy216;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy58;
					goto yy215;
				} else {
					if (yych == 't') goto yy216;
					goto yy58;
				}
			}
yy158:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy218;
			if (yych == 'e') goto yy218;
			goto yy58;
yy159:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy219;
			if (yych == 'u') goto yy219;
			goto yy58;
yy160:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy220;
			if (yych == 'd') goto yy220;
			goto yy58;
yy161:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy221;
				if (yych <= 'H') goto yy58;
				goto yy223;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy58;
					goto yy221;
				} else {
					if (yych == 'i') goto yy223;
					goto yy58;
				}
			}
yy162:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy224;
			if (yych == 'l') goto yy224;
			goto yy58;
yy163:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy225;
			if (yych == 'e') goto yy225;
			goto yy58;
yy164:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy226;
			if (yych == 't') goto yy226;
			goto yy58;
yy165:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '\\') {
				if (yych <= '@') {
					if (yych <= '/') goto yy85;
					if (yych <= ':') goto yy165;
					goto yy85;
				} else {
					if (yych == '[') goto yy85;
					goto yy165;
				}
			} else {
				if (yych <= '_') {
					if (yych <= ']') goto yy227;
					if (yych <= '^') goto yy85;
					goto yy165;
				} else {
					if (yych <= '`') goto yy85;
					if (yych <= 'z') goto yy165;
					goto yy85;
				}
			}
yy167:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 128) {
				goto yy167;
			}
			if (yych == '}') goto yy229;
			goto yy85;
yy169:
			++YYCURSOR;
/* #line 522 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_OR;
			return 0;
		}
/* #line 1349 "scanner.c" */
yy171:
			++YYCURSOR;
/* #line 98 "scanner.re" */
			{
			token->opcode = PHQL_T_SPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 1360 "scanner.c" */
yy173:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy231;
			if (yych == 'i') goto yy231;
			goto yy58;
yy174:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 295 "scanner.re" */
			{
			token->opcode = PHQL_T_ALL;
			return 0;
		}
/* #line 1376 "scanner.c" */
yy176:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 210 "scanner.re" */
			{
			token->opcode = PHQL_T_AND;
			return 0;
		}
/* #line 1387 "scanner.c" */
yy178:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 175 "scanner.re" */
			{
			token->opcode = PHQL_T_ASC;
			return 0;
		}
/* #line 1398 "scanner.c" */
yy180:
			yych = *++YYCURSOR;
			if (yych == 'W') goto yy232;
			if (yych == 'w') goto yy232;
			goto yy58;
yy181:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'E') goto yy233;
				if (yych <= 'S') goto yy58;
				goto yy235;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy58;
					goto yy233;
				} else {
					if (yych == 't') goto yy235;
					goto yy58;
				}
			}
yy182:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy237;
			if (yych == 'v') goto yy237;
			goto yy58;
yy183:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy238;
			if (yych == 's') goto yy238;
			goto yy58;
yy184:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy239;
			if (yych == 'e') goto yy239;
			goto yy58;
yy185:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy240;
			if (yych == 'c') goto yy240;
			goto yy58;
yy186:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy242;
			if (yych == 't') goto yy242;
			goto yy58;
yy187:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy243;
			if (yych == 'e') goto yy243;
			goto yy58;
yy188:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 355 "scanner.re" */
			{
			token->opcode = PHQL_T_END;
			return 0;
		}
/* #line 1459 "scanner.c" */
yy190:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy245;
			if (yych == 's') goto yy245;
			goto yy58;
yy191:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy246;
			if (yych == 's') goto yy246;
			goto yy58;
yy192:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy193;
					if (yych <= ':') goto yy57;
				} else {
					if (yych == 'C') goto yy247;
					if (yych <= 'Z') goto yy57;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy57;
					if (yych == '_') goto yy57;
				} else {
					if (yych == 'c') goto yy247;
					if (yych <= 'z') goto yy57;
				}
			}
yy193:
/* #line 360 "scanner.re" */
			{
			token->opcode = PHQL_T_FOR;
			return 0;
		}
/* #line 1495 "scanner.c" */
yy194:
			yych = *++YYCURSOR;
			if (yych == 'M') goto yy248;
			if (yych == 'm') goto yy248;
			goto yy58;
yy195:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy250;
			if (yych == 'l') goto yy250;
			goto yy58;
yy196:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy252;
			if (yych == 'u') goto yy252;
			goto yy58;
yy197:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy253;
			if (yych == 'i') goto yy253;
			goto yy58;
yy198:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy254;
			if (yych == 'o') goto yy254;
			goto yy58;
yy199:
			yych = *++YYCURSOR;
			if (yych == 'K') goto yy255;
			if (yych == 'k') goto yy255;
			goto yy58;
yy200:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy256;
			if (yych == 'e') goto yy256;
			goto yy58;
yy201:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy257;
			if (yych == 'e') goto yy257;
			goto yy58;
yy202:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy258;
			if (yych == 'e') goto yy258;
			goto yy58;
yy203:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy259;
			if (yych == 'o') goto yy259;
			goto yy58;
yy204:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy261;
			if (yych == 'n') goto yy261;
			goto yy58;
yy205:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy263;
			if (yych == 't') goto yy263;
			goto yy58;
yy206:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy265;
			if (yych == 'e') goto yy265;
			goto yy58;
yy207:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy267;
			if (yych == 'i') goto yy267;
			goto yy58;
yy208:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 205 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 1576 "scanner.c" */
yy210:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy268;
			if (yych == 'l') goto yy268;
			goto yy58;
yy211:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy270;
			if (yych == 's') goto yy270;
			goto yy58;
yy212:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy271;
			if (yych == 'e') goto yy271;
			goto yy58;
yy213:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy272;
			if (yych == 'e') goto yy272;
			goto yy58;
yy214:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy273;
			if (yych == 'h') goto yy273;
			goto yy58;
yy215:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy274;
			if (yych == 'e') goto yy274;
			goto yy58;
yy216:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 120 "scanner.re" */
			{
			token->opcode = PHQL_T_SET;
			return 0;
		}
/* #line 1617 "scanner.c" */
yy218:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy275;
			if (yych == 'n') goto yy275;
			goto yy58;
yy219:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy277;
			if (yych == 'e') goto yy277;
			goto yy58;
yy220:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy279;
			if (yych == 'a') goto yy279;
			goto yy58;
yy221:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 380 "scanner.re" */
			{
			token->opcode = PHQL_T_USE;
			return 0;
		}
/* #line 1643 "scanner.c" */
yy223:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy280;
			if (yych == 'n') goto yy280;
			goto yy58;
yy224:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy281;
			if (yych == 'u') goto yy281;
			goto yy58;
yy225:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'N') goto yy282;
				if (yych <= 'Q') goto yy58;
				goto yy284;
			} else {
				if (yych <= 'n') {
					if (yych <= 'm') goto yy58;
					goto yy282;
				} else {
					if (yych == 'r') goto yy284;
					goto yy58;
				}
			}
yy226:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy285;
			if (yych == 'h') goto yy285;
			goto yy58;
yy227:
			++YYCURSOR;
/* #line 419 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 1684 "scanner.c" */
yy229:
			++YYCURSOR;
/* #line 107 "scanner.re" */
			{
			token->opcode = PHQL_T_BPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 1695 "scanner.c" */
yy231:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy287;
			if (yych == 'n') goto yy287;
			goto yy58;
yy232:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy288;
			if (yych == 'e') goto yy288;
			goto yy58;
yy233:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 335 "scanner.re" */
			{
			token->opcode = PHQL_T_CASE;
			return 0;
		}
/* #line 1716 "scanner.c" */
yy235:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 305 "scanner.re" */
			{
			token->opcode = PHQL_T_CAST;
			return 0;
		}
/* #line 1727 "scanner.c" */
yy237:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy289;
			if (yych == 'e') goto yy289;
			goto yy58;
yy238:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy290;
			if (yych == 's') goto yy290;
			goto yy58;
yy239:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy292;
			if (yych == 't') goto yy292;
			goto yy58;
yy240:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 180 "scanner.re" */
			{
			token->opcode = PHQL_T_DESC;
			return 0;
		}
/* #line 1753 "scanner.c" */
yy242:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy293;
			if (yych == 'i') goto yy293;
			goto yy58;
yy243:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 350 "scanner.re" */
			{
			token->opcode = PHQL_T_ELSE;
			return 0;
		}
/* #line 1769 "scanner.c" */
yy245:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy294;
			if (yych == 't') goto yy294;
			goto yy58;
yy246:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy295;
			if (yych == 'e') goto yy295;
			goto yy58;
yy247:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy297;
			if (yych == 'e') goto yy297;
			goto yy58;
yy248:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 130 "scanner.re" */
			{
			token->opcode = PHQL_T_FROM;
			return 0;
		}
/* #line 1795 "scanner.c" */
yy250:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 275 "scanner.re" */
			{
			token->opcode = PHQL_T_FULL;
			return 0;
		}
/* #line 1806 "scanner.c" */
yy252:
			yych = *++YYCURSOR;
			if (yych == 'P') goto yy299;
			if (yych == 'p') goto yy299;
			goto yy58;
yy253:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy301;
			if (yych == 'n') goto yy301;
			goto yy58;
yy254:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy302;
			if (yych == 'r') goto yy302;
			goto yy58;
yy255:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy303;
			if (yych == 'e') goto yy303;
			goto yy58;
yy256:
			yych = *++YYCURSOR;
			if (yych == 'X') goto yy305;
			if (yych == 'x') goto yy305;
			goto yy58;
yy257:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy307;
			if (yych == 'r') goto yy307;
			goto yy58;
yy258:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy309;
			if (yych == 'r') goto yy309;
			goto yy58;
yy259:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 145 "scanner.re" */
			{
			token->opcode = PHQL_T_INTO;
			return 0;
		}
/* #line 1852 "scanner.c" */
yy261:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 245 "scanner.re" */
			{
			token->opcode = PHQL_T_JOIN;
			return 0;
		}
/* #line 1863 "scanner.c" */
yy263:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 255 "scanner.re" */
			{
			token->opcode = PHQL_T_LEFT;
			return 0;
		}
/* #line 1874 "scanner.c" */
yy265:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 220 "scanner.re" */
			{
			token->opcode = PHQL_T_LIKE;
			return 0;
		}
/* #line 1885 "scanner.c" */
yy267:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy310;
			if (yych == 't') goto yy310;
			goto yy58;
yy268:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 285 "scanner.re" */
			{
			token->opcode = PHQL_T_NULL;
			return 0;
		}
/* #line 1901 "scanner.c" */
yy270:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy312;
			if (yych == 'e') goto yy312;
			goto yy58;
yy271:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy313;
			if (yych == 'r') goto yy313;
			goto yy58;
yy272:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy315;
			if (yych == 'r') goto yy315;
			goto yy58;
yy273:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy317;
			if (yych == 't') goto yy317;
			goto yy58;
yy274:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy319;
			if (yych == 'c') goto yy319;
			goto yy58;
yy275:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 345 "scanner.re" */
			{
			token->opcode = PHQL_T_THEN;
			return 0;
		}
/* #line 1937 "scanner.c" */
yy277:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 325 "scanner.re" */
			{
			token->opcode = PHQL_T_TRUE;
			return 0;
		}
/* #line 1948 "scanner.c" */
yy279:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy320;
			if (yych == 't') goto yy320;
			goto yy58;
yy280:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy321;
			if (yych == 'g') goto yy321;
			goto yy58;
yy281:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy323;
			if (yych == 'e') goto yy323;
			goto yy58;
yy282:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 340 "scanner.re" */
			{
			token->opcode = PHQL_T_WHEN;
			return 0;
		}
/* #line 1974 "scanner.c" */
yy284:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy324;
			if (yych == 'e') goto yy324;
			goto yy58;
yy285:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 365 "scanner.re" */
			{
			token->opcode = PHQL_T_WITH;
			return 0;
		}
/* #line 1990 "scanner.c" */
yy287:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy326;
			if (yych == 's') goto yy326;
			goto yy58;
yy288:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy327;
			if (yych == 'e') goto yy327;
			goto yy58;
yy289:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy328;
			if (yych == 'r') goto yy328;
			goto yy58;
yy290:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 265 "scanner.re" */
			{
			token->opcode = PHQL_T_CROSS;
			return 0;
		}
/* #line 2016 "scanner.c" */
yy292:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy329;
			if (yych == 'e') goto yy329;
			goto yy58;
yy293:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy331;
			if (yych == 'n') goto yy331;
			goto yy58;
yy294:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy332;
			if (yych == 's') goto yy332;
			goto yy58;
yy295:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 330 "scanner.re" */
			{
			token->opcode = PHQL_T_FALSE;
			return 0;
		}
/* #line 2042 "scanner.c" */
yy297:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 370 "scanner.re" */
			{
			token->opcode = PHQL_T_FORCE;
			return 0;
		}
/* #line 2053 "scanner.c" */
yy299:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 185 "scanner.re" */
			{
			token->opcode = PHQL_T_GROUP;
			return 0;
		}
/* #line 2064 "scanner.c" */
yy301:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy334;
			if (yych == 'g') goto yy334;
			goto yy58;
yy302:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy336;
			if (yych == 'e') goto yy336;
			goto yy58;
yy303:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 225 "scanner.re" */
			{
			token->opcode = PHQL_T_ILIKE;
			return 0;
		}
/* #line 2085 "scanner.c" */
yy305:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 385 "scanner.re" */
			{
			token->opcode = PHQL_T_INDEX;
			return 0;
		}
/* #line 2096 "scanner.c" */
yy307:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 250 "scanner.re" */
			{
			token->opcode = PHQL_T_INNER;
			return 0;
		}
/* #line 2107 "scanner.c" */
yy309:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy338;
			if (yych == 't') goto yy338;
			goto yy58;
yy310:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 195 "scanner.re" */
			{
			token->opcode = PHQL_T_LIMIT;
			return 0;
		}
/* #line 2123 "scanner.c" */
yy312:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy340;
			if (yych == 't') goto yy340;
			goto yy58;
yy313:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 165 "scanner.re" */
			{
			token->opcode = PHQL_T_ORDER;
			return 0;
		}
/* #line 2139 "scanner.c" */
yy315:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 270 "scanner.re" */
			{
			token->opcode = PHQL_T_OUTER;
			return 0;
		}
/* #line 2150 "scanner.c" */
yy317:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 260 "scanner.re" */
			{
			token->opcode = PHQL_T_RIGHT;
			return 0;
		}
/* #line 2161 "scanner.c" */
yy319:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy342;
			if (yych == 't') goto yy342;
			goto yy58;
yy320:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy344;
			if (yych == 'e') goto yy344;
			goto yy58;
yy321:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 315 "scanner.re" */
			{
			token->opcode = PHQL_T_USING;
			return 0;
		}
/* #line 2182 "scanner.c" */
yy323:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy346;
			if (yych == 's') goto yy346;
			goto yy58;
yy324:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 155 "scanner.re" */
			{
			token->opcode = PHQL_T_WHERE;
			return 0;
		}
/* #line 2198 "scanner.c" */
yy326:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy348;
			if (yych == 't') goto yy348;
			goto yy58;
yy327:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy350;
			if (yych == 'n') goto yy350;
			goto yy58;
yy328:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy352;
			if (yych == 't') goto yy352;
			goto yy58;
yy329:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 125 "scanner.re" */
			{
			token->opcode = PHQL_T_DELETE;
			return 0;
		}
/* #line 2224 "scanner.c" */
yy331:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy354;
			if (yych == 'c') goto yy354;
			goto yy58;
yy332:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 320 "scanner.re" */
			{
			token->opcode = PHQL_T_EXISTS;
			return 0;
		}
/* #line 2240 "scanner.c" */
yy334:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 190 "scanner.re" */
			{
			token->opcode = PHQL_T_HAVING;
			return 0;
		}
/* #line 2251 "scanner.c" */
yy336:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 375 "scanner.re" */
			{
			token->opcode = PHQL_T_IGNORE;
			return 0;
		}
/* #line 2262 "scanner.c" */
yy338:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 140 "scanner.re" */
			{
			token->opcode = PHQL_T_INSERT;
			return 0;
		}
/* #line 2273 "scanner.c" */
yy340:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 200 "scanner.re" */
			{
			token->opcode = PHQL_T_OFFSET;
			return 0;
		}
/* #line 2284 "scanner.c" */
yy342:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 160 "scanner.re" */
			{
			token->opcode = PHQL_T_SELECT;
			return 0;
		}
/* #line 2295 "scanner.c" */
yy344:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 115 "scanner.re" */
			{
			token->opcode = PHQL_T_UPDATE;
			return 0;
		}
/* #line 2306 "scanner.c" */
yy346:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 150 "scanner.re" */
			{
			token->opcode = PHQL_T_VALUES;
			return 0;
		}
/* #line 2317 "scanner.c" */
yy348:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 230 "scanner.re" */
			{
			token->opcode = PHQL_T_AGAINST;
			return 0;
		}
/* #line 2328 "scanner.c" */
yy350:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 300 "scanner.re" */
			{
			token->opcode = PHQL_T_BETWEEN;
			return 0;
		}
/* #line 2339 "scanner.c" */
yy352:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 310 "scanner.re" */
			{
			token->opcode = PHQL_T_CONVERT;
			return 0;
		}
/* #line 2350 "scanner.c" */
yy354:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy355;
			if (yych != 't') goto yy58;
yy355:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 290 "scanner.re" */
			{
			token->opcode = PHQL_T_DISTINCT;
			return 0;
		}
/* #line 2365 "scanner.c" */
		}
/* #line 587 "scanner.re" */

	}

	return status;
}
