/* Generated by re2c 0.16 on Mon Aug 29 14:24:20 2016 */
/* #line 1 "scanner.re" */

/*
  +------------------------------------------------------------------------+
  | Phalcon Framework                                                      |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2016 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  +------------------------------------------------------------------------+
*/

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include "php_phalcon.h"

#include "scanner.h"

#define YYCTYPE unsigned char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER q

int phql_get_token(phql_scanner_state *s, phql_scanner_token *token) {

	char *q = YYCURSOR;
	int status = PHQL_SCANNER_RETCODE_IMPOSSIBLE;

	while (PHQL_SCANNER_RETCODE_IMPOSSIBLE == status) {

		
/* #line 45 "scanner.c" */
		{
			YYCTYPE yych;
			unsigned int yyaccept = 0;
			static const unsigned char yybm[] = {
				  0,  48,  48,  48,  48,  48,  48,  48, 
				 48,  49,  49,  48,  48,  49,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 49,  48,  32,  48,  48,  48,  48,  16, 
				 48,  48,  48,  48,  48, 240,  48,  48, 
				254, 254, 254, 254, 254, 254, 254, 254, 
				254, 254, 180,  48,  48,  48,  48,  48, 
				 48, 252, 252, 252, 252, 252, 252, 244, 
				244, 244, 244, 244, 244, 244, 244, 244, 
				244, 244, 244, 244, 244, 244, 244, 244, 
				244, 244, 244,  48,   4,  48,  48, 244, 
				 48, 252, 252, 252, 252, 252, 252, 244, 
				244, 244, 244, 244, 244, 244, 244, 244, 
				244, 244, 244, 244, 244, 244, 244, 244, 
				252, 244, 244,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
				 48,  48,  48,  48,  48,  48,  48,  48, 
			};
			yych = *YYCURSOR;
			if (yybm[0+yych] & 1) {
				goto yy6;
			}
			switch (yych) {
			case 0x00:	goto yy2;
			case ' ':
			case '!':	goto yy9;
			case '"':	goto yy11;
			case '%':	goto yy12;
			case '&':	goto yy14;
			case '\'':	goto yy16;
			case '(':	goto yy17;
			case ')':	goto yy19;
			case '*':	goto yy21;
			case '+':	goto yy23;
			case ',':	goto yy25;
			case '-':	goto yy27;
			case '.':	goto yy29;
			case '/':	goto yy31;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy33;
			case ':':	goto yy36;
			case '<':	goto yy38;
			case '=':	goto yy40;
			case '>':	goto yy42;
			case '?':	goto yy44;
			case '@':	goto yy45;
			case 'A':
			case 'a':	goto yy46;
			case 'B':
			case 'b':	goto yy47;
			case 'C':
			case 'c':	goto yy48;
			case 'D':
			case 'd':	goto yy49;
			case 'E':
			case 'e':	goto yy50;
			case 'F':
			case 'f':	goto yy51;
			case 'G':
			case 'g':	goto yy52;
			case 'H':
			case 'h':	goto yy54;
			case 'I':
			case 'i':	goto yy55;
			case 'J':
			case 'j':	goto yy56;
			case 'K':
			case 'M':
			case 'P':
			case 'Q':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'k':
			case 'm':
			case 'p':
			case 'q':
			case 'y':
			case 'z':	goto yy57;
			case 'L':
			case 'l':	goto yy59;
			case 'N':
			case 'n':	goto yy60;
			case 'O':
			case 'o':	goto yy61;
			case 'R':
			case 'r':	goto yy62;
			case 'S':
			case 's':	goto yy63;
			case 'T':
			case 't':	goto yy64;
			case 'U':
			case 'u':	goto yy65;
			case 'V':
			case 'v':	goto yy66;
			case 'W':
			case 'w':	goto yy67;
			case '[':	goto yy68;
			case '\\':	goto yy69;
			case '^':	goto yy70;
			case 'x':	goto yy72;
			case '{':	goto yy74;
			case '|':	goto yy75;
			case '~':	goto yy77;
			default:	goto yy4;
			}
yy2:
			++YYCURSOR;
/* #line 552 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_EOF;
			break;
		}
/* #line 187 "scanner.c" */
yy4:
			++YYCURSOR;
yy5:
/* #line 557 "scanner.re" */
			{
			status = PHQL_SCANNER_RETCODE_ERR;
			break;
		}
/* #line 196 "scanner.c" */
yy6:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 1) {
				goto yy6;
			}
/* #line 547 "scanner.re" */
			{
			token->opcode = PHQL_T_IGNORE;
			return 0;
		}
/* #line 208 "scanner.c" */
yy9:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '!') goto yy79;
			if (yych == '=') goto yy81;
/* #line 522 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 218 "scanner.c" */
yy11:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy5;
			goto yy84;
yy12:
			++YYCURSOR;
/* #line 427 "scanner.re" */
			{
			token->opcode = PHQL_T_MOD;
			return 0;
		}
/* #line 231 "scanner.c" */
yy14:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '&') goto yy89;
/* #line 537 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_AND;
			return 0;
		}
/* #line 240 "scanner.c" */
yy16:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= 0x00) goto yy5;
			goto yy92;
yy17:
			++YYCURSOR;
/* #line 447 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_OPEN;
			return 0;
		}
/* #line 253 "scanner.c" */
yy19:
			++YYCURSOR;
/* #line 452 "scanner.re" */
			{
			token->opcode = PHQL_T_PARENTHESES_CLOSE;
			return 0;
		}
/* #line 261 "scanner.c" */
yy21:
			++YYCURSOR;
/* #line 417 "scanner.re" */
			{
			token->opcode = PHQL_T_MUL;
			return 0;
		}
/* #line 269 "scanner.c" */
yy23:
			++YYCURSOR;
/* #line 407 "scanner.re" */
			{
			token->opcode = PHQL_T_ADD;
			return 0;
		}
/* #line 277 "scanner.c" */
yy25:
			++YYCURSOR;
/* #line 442 "scanner.re" */
			{
			token->opcode = PHQL_T_COMMA;
			return 0;
		}
/* #line 285 "scanner.c" */
yy27:
			++YYCURSOR;
/* #line 412 "scanner.re" */
			{
			token->opcode = PHQL_T_SUB;
			return 0;
		}
/* #line 293 "scanner.c" */
yy29:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '/') goto yy30;
			if (yych <= '9') goto yy94;
yy30:
/* #line 432 "scanner.re" */
			{
			token->opcode = PHQL_T_DOT;
			return 0;
		}
/* #line 304 "scanner.c" */
yy31:
			++YYCURSOR;
/* #line 422 "scanner.re" */
			{
			token->opcode = PHQL_T_DIV;
			return 0;
		}
/* #line 312 "scanner.c" */
yy33:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 2) {
				goto yy33;
			}
			if (yych <= 'F') {
				if (yych == '.') goto yy94;
				if (yych >= 'A') goto yy97;
			} else {
				if (yych <= 'f') {
					if (yych >= 'a') goto yy97;
				} else {
					if (yych == 'x') goto yy97;
				}
			}
yy35:
/* #line 46 "scanner.re" */
			{
            token->value = estrndup(q, YYCURSOR - q);
            token->len = YYCURSOR - q;
            if (token->len > 2 && !memcmp(token->value, "0x", 2)) {
			    token->opcode = PHQL_T_HINTEGER;
            } else {
                int i, alpha = 0;
                for (i = 0; i < token->len; i++) {
                    unsigned char ch = token->value[i];
                    if (!((ch >= '0') && (ch <= '9'))) {
                        alpha = 1;
                        break;
                    }
                }
                if (alpha) {
                    token->opcode = PHQL_T_IDENTIFIER;
                } else {
                    token->opcode = PHQL_T_INTEGER;
                }
            }
			q = YYCURSOR;
			return 0;
		}
/* #line 354 "scanner.c" */
yy36:
			yyaccept = 1;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 64) {
				goto yy99;
			}
yy37:
/* #line 437 "scanner.re" */
			{
			token->opcode = PHQL_T_COLON;
			return 0;
		}
/* #line 367 "scanner.c" */
yy38:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '<') goto yy39;
			if (yych <= '=') goto yy101;
			if (yych <= '>') goto yy103;
yy39:
/* #line 477 "scanner.re" */
			{
			token->opcode = PHQL_T_LESS;
			return 0;
		}
/* #line 379 "scanner.c" */
yy40:
			++YYCURSOR;
/* #line 487 "scanner.re" */
			{
			token->opcode = PHQL_T_EQUALS;
			return 0;
		}
/* #line 387 "scanner.c" */
yy42:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '=') goto yy105;
/* #line 482 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATER;
			return 0;
		}
/* #line 396 "scanner.c" */
yy44:
			yych = *++YYCURSOR;
			if (yych <= '/') goto yy5;
			if (yych <= '9') goto yy107;
			goto yy5;
yy45:
			yych = *++YYCURSOR;
			if (yych == '>') goto yy110;
			if (yych == '@') goto yy112;
			goto yy5;
yy46:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy114;
			case 'L':
			case 'l':	goto yy115;
			case 'N':
			case 'n':	goto yy116;
			case 'S':
			case 's':	goto yy117;
			default:	goto yy73;
			}
yy47:
			yych = *++YYCURSOR;
			if (yych <= 'Y') {
				if (yych == 'E') goto yy119;
				if (yych <= 'X') goto yy73;
				goto yy120;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy73;
					goto yy119;
				} else {
					if (yych == 'y') goto yy120;
					goto yy73;
				}
			}
yy48:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych <= 'N') {
					if (yych == 'A') goto yy122;
					goto yy73;
				} else {
					if (yych <= 'O') goto yy123;
					if (yych <= 'Q') goto yy73;
					goto yy124;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'a') goto yy122;
					goto yy73;
				} else {
					if (yych <= 'o') goto yy123;
					if (yych == 'r') goto yy124;
					goto yy73;
				}
			}
yy49:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy125;
				if (yych <= 'H') goto yy73;
				goto yy126;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy73;
					goto yy125;
				} else {
					if (yych == 'i') goto yy126;
					goto yy73;
				}
			}
yy50:
			yych = *++YYCURSOR;
			if (yych <= 'X') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy127;
					goto yy73;
				} else {
					if (yych <= 'N') goto yy128;
					if (yych <= 'W') goto yy73;
					goto yy129;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy127;
					goto yy73;
				} else {
					if (yych <= 'n') goto yy128;
					if (yych == 'x') goto yy130;
					goto yy73;
				}
			}
yy51:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'O') {
					if (yych == 'A') goto yy131;
					if (yych <= 'N') goto yy73;
					goto yy132;
				} else {
					if (yych == 'R') goto yy133;
					if (yych <= 'T') goto yy73;
					goto yy134;
				}
			} else {
				if (yych <= 'o') {
					if (yych == 'a') goto yy131;
					if (yych <= 'n') goto yy73;
					goto yy132;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy73;
						goto yy133;
					} else {
						if (yych == 'u') goto yy134;
						goto yy73;
					}
				}
			}
yy52:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == 'R') goto yy135;
			if (yych == 'r') goto yy135;
			goto yy58;
yy53:
/* #line 380 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			if ((YYCURSOR - q) > 1) {
				if (q[0] == '\\') {
					token->value = estrndup(q + 1, YYCURSOR - q - 1);
					token->len = YYCURSOR - q - 1;
				} else {
					token->value = estrndup(q, YYCURSOR - q);
					token->len = YYCURSOR - q;
				}
			} else {
				token->value = estrndup(q, YYCURSOR - q);
				token->len = YYCURSOR - q;
			}
			q = YYCURSOR;
			return 0;
		}
/* #line 543 "scanner.c" */
yy54:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy136;
			if (yych == 'a') goto yy136;
			goto yy58;
yy55:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych <= 'M') {
					if (yych == 'L') goto yy137;
					goto yy58;
				} else {
					if (yych <= 'N') goto yy138;
					if (yych <= 'R') goto yy58;
					goto yy140;
				}
			} else {
				if (yych <= 'm') {
					if (yych == 'l') goto yy137;
					goto yy58;
				} else {
					if (yych <= 'n') goto yy138;
					if (yych == 's') goto yy140;
					goto yy58;
				}
			}
yy56:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy142;
			if (yych == 'o') goto yy142;
			goto yy58;
yy57:
			++YYCURSOR;
			yych = *YYCURSOR;
yy58:
			if (yybm[0+yych] & 4) {
				goto yy57;
			}
			goto yy53;
yy59:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych == 'E') goto yy143;
				if (yych <= 'H') goto yy58;
				goto yy144;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy58;
					goto yy143;
				} else {
					if (yych == 'i') goto yy144;
					goto yy58;
				}
			}
yy60:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych == 'O') goto yy145;
				if (yych <= 'T') goto yy58;
				goto yy146;
			} else {
				if (yych <= 'o') {
					if (yych <= 'n') goto yy58;
					goto yy145;
				} else {
					if (yych == 'u') goto yy146;
					goto yy58;
				}
			}
yy61:
			yych = *++YYCURSOR;
			if (yych <= 'U') {
				if (yych <= 'N') {
					if (yych == 'F') goto yy147;
					if (yych <= 'M') goto yy58;
					goto yy148;
				} else {
					if (yych == 'R') goto yy150;
					if (yych <= 'T') goto yy58;
					goto yy152;
				}
			} else {
				if (yych <= 'n') {
					if (yych == 'f') goto yy147;
					if (yych <= 'm') goto yy58;
					goto yy148;
				} else {
					if (yych <= 'r') {
						if (yych <= 'q') goto yy58;
						goto yy150;
					} else {
						if (yych == 'u') goto yy152;
						goto yy58;
					}
				}
			}
yy62:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy153;
			if (yych == 'i') goto yy153;
			goto yy58;
yy63:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy154;
			if (yych == 'e') goto yy154;
			goto yy58;
yy64:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'H') goto yy155;
				if (yych <= 'Q') goto yy58;
				goto yy156;
			} else {
				if (yych <= 'h') {
					if (yych <= 'g') goto yy58;
					goto yy155;
				} else {
					if (yych == 'r') goto yy156;
					goto yy58;
				}
			}
yy65:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych == 'P') goto yy157;
				if (yych <= 'R') goto yy58;
				goto yy158;
			} else {
				if (yych <= 'p') {
					if (yych <= 'o') goto yy58;
					goto yy157;
				} else {
					if (yych == 's') goto yy158;
					goto yy58;
				}
			}
yy66:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy159;
			if (yych == 'a') goto yy159;
			goto yy58;
yy67:
			yych = *++YYCURSOR;
			if (yych <= 'I') {
				if (yych <= 'G') goto yy58;
				if (yych <= 'H') goto yy160;
				goto yy161;
			} else {
				if (yych <= 'g') goto yy58;
				if (yych <= 'h') goto yy160;
				if (yych <= 'i') goto yy161;
				goto yy58;
			}
yy68:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yych <= '\\') {
				if (yych <= '@') goto yy5;
				if (yych == '[') goto yy5;
				goto yy162;
			} else {
				if (yych <= '_') {
					if (yych <= '^') goto yy5;
					goto yy162;
				} else {
					if (yych <= '`') goto yy5;
					if (yych <= 'z') goto yy162;
					goto yy5;
				}
			}
yy69:
			yych = *++YYCURSOR;
			if (yych <= '^') {
				if (yych <= '@') goto yy5;
				if (yych <= 'Z') goto yy57;
				goto yy5;
			} else {
				if (yych == '`') goto yy5;
				if (yych <= 'z') goto yy57;
				goto yy5;
			}
yy70:
			++YYCURSOR;
/* #line 532 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_XOR;
			return 0;
		}
/* #line 732 "scanner.c" */
yy72:
			++YYCURSOR;
			yych = *YYCURSOR;
yy73:
			if (yybm[0+yych] & 8) {
				goto yy72;
			}
			if (yych <= '[') {
				if (yych <= ':') {
					if (yych <= '/') goto yy35;
					goto yy57;
				} else {
					if (yych <= '@') goto yy35;
					if (yych <= 'Z') goto yy57;
					goto yy35;
				}
			} else {
				if (yych <= '_') {
					if (yych <= '\\') goto yy57;
					if (yych <= '^') goto yy35;
					goto yy57;
				} else {
					if (yych <= '`') goto yy35;
					if (yych <= 'z') goto yy57;
					goto yy35;
				}
			}
yy74:
			yyaccept = 0;
			yych = *(YYMARKER = ++YYCURSOR);
			if (yybm[0+yych] & 128) {
				goto yy164;
			}
			goto yy5;
yy75:
			++YYCURSOR;
			if ((yych = *YYCURSOR) == '|') goto yy166;
/* #line 542 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_OR;
			return 0;
		}
/* #line 775 "scanner.c" */
yy77:
			++YYCURSOR;
/* #line 527 "scanner.re" */
			{
			token->opcode = PHQL_T_BITWISE_NOT;
			return 0;
		}
/* #line 783 "scanner.c" */
yy79:
			++YYCURSOR;
/* #line 507 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_NEGATE;
			return 0;
		}
/* #line 791 "scanner.c" */
yy81:
			++YYCURSOR;
/* #line 457 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 799 "scanner.c" */
yy83:
			++YYCURSOR;
			yych = *YYCURSOR;
yy84:
			if (yybm[0+yych] & 16) {
				goto yy83;
			}
			if (yych <= 0x00) goto yy85;
			if (yych <= '"') goto yy86;
			goto yy88;
yy85:
			YYCURSOR = YYMARKER;
			if (yyaccept == 0) {
				goto yy5;
			} else {
				goto yy37;
			}
yy86:
			++YYCURSOR;
/* #line 371 "scanner.re" */
			{
			token->opcode = PHQL_T_STRING;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 827 "scanner.c" */
yy88:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy85;
			goto yy83;
yy89:
			++YYCURSOR;
/* #line 502 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_AND;
			return 0;
		}
/* #line 840 "scanner.c" */
yy91:
			++YYCURSOR;
			yych = *YYCURSOR;
yy92:
			if (yybm[0+yych] & 32) {
				goto yy91;
			}
			if (yych <= 0x00) goto yy85;
			if (yych <= '\'') goto yy86;
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych == '\n') goto yy85;
			goto yy91;
yy94:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy96;
			if (yych <= '9') goto yy94;
yy96:
/* #line 80 "scanner.re" */
			{
			token->opcode = PHQL_T_DOUBLE;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 868 "scanner.c" */
yy97:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= 'F') {
				if (yych <= '/') goto yy35;
				if (yych <= '9') goto yy97;
				if (yych <= '@') goto yy35;
				goto yy97;
			} else {
				if (yych <= 'f') {
					if (yych <= '`') goto yy35;
					goto yy97;
				} else {
					if (yych == 'x') goto yy97;
					goto yy35;
				}
			}
yy99:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 64) {
				goto yy99;
			}
			if (yych <= '/') goto yy85;
			if (yych <= ':') goto yy168;
			goto yy85;
yy101:
			++YYCURSOR;
/* #line 467 "scanner.re" */
			{
			token->opcode = PHQL_T_LESSEQUAL;
			return 0;
		}
/* #line 902 "scanner.c" */
yy103:
			++YYCURSOR;
/* #line 462 "scanner.re" */
			{
			token->opcode = PHQL_T_NOTEQUALS;
			return 0;
		}
/* #line 910 "scanner.c" */
yy105:
			++YYCURSOR;
/* #line 472 "scanner.re" */
			{
			token->opcode = PHQL_T_GREATEREQUAL;
			return 0;
		}
/* #line 918 "scanner.c" */
yy107:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '/') goto yy109;
			if (yych <= '9') goto yy107;
yy109:
/* #line 89 "scanner.re" */
			{
			token->opcode = PHQL_T_NPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q);
			token->len = YYCURSOR - q;
			q = YYCURSOR;
			return 0;
		}
/* #line 933 "scanner.c" */
yy110:
			++YYCURSOR;
/* #line 512 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_CONTAINS_ANOTHER;
			return 0;
		}
/* #line 941 "scanner.c" */
yy112:
			++YYCURSOR;
/* #line 492 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_MATCHES;
			return 0;
		}
/* #line 949 "scanner.c" */
yy114:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy170;
			if (yych == 'a') goto yy170;
			goto yy58;
yy115:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy171;
			if (yych == 'l') goto yy171;
			goto yy58;
yy116:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy173;
			if (yych == 'd') goto yy173;
			goto yy58;
yy117:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy118;
					if (yych <= ':') goto yy57;
				} else {
					if (yych == 'C') goto yy175;
					if (yych <= 'Z') goto yy57;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy57;
					if (yych == '_') goto yy57;
				} else {
					if (yych == 'c') goto yy175;
					if (yych <= 'z') goto yy57;
				}
			}
yy118:
/* #line 135 "scanner.re" */
			{
			token->opcode = PHQL_T_AS;
			return 0;
		}
/* #line 990 "scanner.c" */
yy119:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy177;
			if (yych == 't') goto yy177;
			goto yy73;
yy120:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 170 "scanner.re" */
			{
			token->opcode = PHQL_T_BY;
			return 0;
		}
/* #line 1006 "scanner.c" */
yy122:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy178;
			if (yych == 's') goto yy178;
			goto yy73;
yy123:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy179;
			if (yych == 'n') goto yy179;
			goto yy58;
yy124:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy180;
			if (yych == 'o') goto yy180;
			goto yy58;
yy125:
			yych = *++YYCURSOR;
			if (yych <= 'S') {
				if (yych == 'L') goto yy181;
				if (yych <= 'R') goto yy73;
				goto yy182;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy73;
					goto yy181;
				} else {
					if (yych == 's') goto yy182;
					goto yy73;
				}
			}
yy126:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy183;
			if (yych == 's') goto yy183;
			goto yy58;
yy127:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy184;
			if (yych == 's') goto yy184;
			goto yy58;
yy128:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy185;
			if (yych == 'd') goto yy185;
			goto yy58;
yy129:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy187;
			if (yych == 'i') goto yy187;
			goto yy58;
yy130:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy187;
			if (yych == 'i') goto yy187;
			goto yy73;
yy131:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy188;
			if (yych == 'l') goto yy188;
			goto yy73;
yy132:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy189;
			if (yych == 'r') goto yy189;
			goto yy58;
yy133:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy191;
			if (yych == 'o') goto yy191;
			goto yy58;
yy134:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy192;
			if (yych == 'l') goto yy192;
			goto yy58;
yy135:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy193;
			if (yych == 'o') goto yy193;
			goto yy58;
yy136:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy194;
			if (yych == 'v') goto yy194;
			goto yy58;
yy137:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy195;
			if (yych == 'i') goto yy195;
			goto yy58;
yy138:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= 'N') {
					if (yych <= ':') {
						if (yych >= '0') goto yy57;
					} else {
						if (yych <= '@') goto yy139;
						if (yych <= 'M') goto yy57;
						goto yy196;
					}
				} else {
					if (yych <= 'S') {
						if (yych <= 'R') goto yy57;
						goto yy197;
					} else {
						if (yych <= 'T') goto yy198;
						if (yych <= 'Z') goto yy57;
					}
				}
			} else {
				if (yych <= 'm') {
					if (yych <= '^') {
						if (yych <= '\\') goto yy57;
					} else {
						if (yych != '`') goto yy57;
					}
				} else {
					if (yych <= 's') {
						if (yych <= 'n') goto yy196;
						if (yych <= 'r') goto yy57;
						goto yy197;
					} else {
						if (yych <= 't') goto yy198;
						if (yych <= 'z') goto yy57;
					}
				}
			}
yy139:
/* #line 235 "scanner.re" */
			{
			token->opcode = PHQL_T_IN;
			return 0;
		}
/* #line 1141 "scanner.c" */
yy140:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 280 "scanner.re" */
			{
			token->opcode = PHQL_T_IS;
			return 0;
		}
/* #line 1152 "scanner.c" */
yy142:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy199;
			if (yych == 'i') goto yy199;
			goto yy58;
yy143:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy200;
			if (yych == 'f') goto yy200;
			goto yy58;
yy144:
			yych = *++YYCURSOR;
			if (yych <= 'M') {
				if (yych == 'K') goto yy201;
				if (yych <= 'L') goto yy58;
				goto yy202;
			} else {
				if (yych <= 'k') {
					if (yych <= 'j') goto yy58;
					goto yy201;
				} else {
					if (yych == 'm') goto yy202;
					goto yy58;
				}
			}
yy145:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy203;
			if (yych == 't') goto yy203;
			goto yy58;
yy146:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy205;
			if (yych == 'l') goto yy205;
			goto yy58;
yy147:
			yych = *++YYCURSOR;
			if (yych == 'F') goto yy206;
			if (yych == 'f') goto yy206;
			goto yy58;
yy148:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 240 "scanner.re" */
			{
			token->opcode = PHQL_T_ON;
			return 0;
		}
/* #line 1203 "scanner.c" */
yy150:
			++YYCURSOR;
			if ((yych = *YYCURSOR) <= '[') {
				if (yych <= '@') {
					if (yych <= '/') goto yy151;
					if (yych <= ':') goto yy57;
				} else {
					if (yych == 'D') goto yy207;
					if (yych <= 'Z') goto yy57;
				}
			} else {
				if (yych <= '`') {
					if (yych <= '\\') goto yy57;
					if (yych == '_') goto yy57;
				} else {
					if (yych == 'd') goto yy207;
					if (yych <= 'z') goto yy57;
				}
			}
yy151:
/* #line 215 "scanner.re" */
			{
			token->opcode = PHQL_T_OR;
			return 0;
		}
/* #line 1229 "scanner.c" */
yy152:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy208;
			if (yych == 't') goto yy208;
			goto yy58;
yy153:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy209;
			if (yych == 'g') goto yy209;
			goto yy58;
yy154:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'L') goto yy210;
				if (yych <= 'S') goto yy58;
				goto yy211;
			} else {
				if (yych <= 'l') {
					if (yych <= 'k') goto yy58;
					goto yy210;
				} else {
					if (yych == 't') goto yy211;
					goto yy58;
				}
			}
yy155:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy213;
			if (yych == 'e') goto yy213;
			goto yy58;
yy156:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy214;
			if (yych == 'u') goto yy214;
			goto yy58;
yy157:
			yych = *++YYCURSOR;
			if (yych == 'D') goto yy215;
			if (yych == 'd') goto yy215;
			goto yy58;
yy158:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy216;
			if (yych == 'i') goto yy216;
			goto yy58;
yy159:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy217;
			if (yych == 'l') goto yy217;
			goto yy58;
yy160:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy218;
			if (yych == 'e') goto yy218;
			goto yy58;
yy161:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy219;
			if (yych == 't') goto yy219;
			goto yy58;
yy162:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yych <= '\\') {
				if (yych <= '@') {
					if (yych <= '/') goto yy85;
					if (yych <= ':') goto yy162;
					goto yy85;
				} else {
					if (yych == '[') goto yy85;
					goto yy162;
				}
			} else {
				if (yych <= '_') {
					if (yych <= ']') goto yy220;
					if (yych <= '^') goto yy85;
					goto yy162;
				} else {
					if (yych <= '`') goto yy85;
					if (yych <= 'z') goto yy162;
					goto yy85;
				}
			}
yy164:
			++YYCURSOR;
			yych = *YYCURSOR;
			if (yybm[0+yych] & 128) {
				goto yy164;
			}
			if (yych == '}') goto yy222;
			goto yy85;
yy166:
			++YYCURSOR;
/* #line 497 "scanner.re" */
			{
			token->opcode = PHQL_T_TS_OR;
			return 0;
		}
/* #line 1328 "scanner.c" */
yy168:
			++YYCURSOR;
/* #line 98 "scanner.re" */
			{
			token->opcode = PHQL_T_SPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 1339 "scanner.c" */
yy170:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy224;
			if (yych == 'i') goto yy224;
			goto yy58;
yy171:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 295 "scanner.re" */
			{
			token->opcode = PHQL_T_ALL;
			return 0;
		}
/* #line 1355 "scanner.c" */
yy173:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 210 "scanner.re" */
			{
			token->opcode = PHQL_T_AND;
			return 0;
		}
/* #line 1366 "scanner.c" */
yy175:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 175 "scanner.re" */
			{
			token->opcode = PHQL_T_ASC;
			return 0;
		}
/* #line 1377 "scanner.c" */
yy177:
			yych = *++YYCURSOR;
			if (yych == 'W') goto yy225;
			if (yych == 'w') goto yy225;
			goto yy58;
yy178:
			yych = *++YYCURSOR;
			if (yych <= 'T') {
				if (yych == 'E') goto yy226;
				if (yych <= 'S') goto yy58;
				goto yy228;
			} else {
				if (yych <= 'e') {
					if (yych <= 'd') goto yy58;
					goto yy226;
				} else {
					if (yych == 't') goto yy228;
					goto yy58;
				}
			}
yy179:
			yych = *++YYCURSOR;
			if (yych == 'V') goto yy230;
			if (yych == 'v') goto yy230;
			goto yy58;
yy180:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy231;
			if (yych == 's') goto yy231;
			goto yy58;
yy181:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy232;
			if (yych == 'e') goto yy232;
			goto yy58;
yy182:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy233;
			if (yych == 'c') goto yy233;
			goto yy58;
yy183:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy235;
			if (yych == 't') goto yy235;
			goto yy58;
yy184:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy236;
			if (yych == 'e') goto yy236;
			goto yy58;
yy185:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 355 "scanner.re" */
			{
			token->opcode = PHQL_T_END;
			return 0;
		}
/* #line 1438 "scanner.c" */
yy187:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy238;
			if (yych == 's') goto yy238;
			goto yy58;
yy188:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy239;
			if (yych == 's') goto yy239;
			goto yy58;
yy189:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 360 "scanner.re" */
			{
			token->opcode = PHQL_T_FOR;
			return 0;
		}
/* #line 1459 "scanner.c" */
yy191:
			yych = *++YYCURSOR;
			if (yych == 'M') goto yy240;
			if (yych == 'm') goto yy240;
			goto yy58;
yy192:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy242;
			if (yych == 'l') goto yy242;
			goto yy58;
yy193:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy244;
			if (yych == 'u') goto yy244;
			goto yy58;
yy194:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy245;
			if (yych == 'i') goto yy245;
			goto yy58;
yy195:
			yych = *++YYCURSOR;
			if (yych == 'K') goto yy246;
			if (yych == 'k') goto yy246;
			goto yy58;
yy196:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy247;
			if (yych == 'e') goto yy247;
			goto yy58;
yy197:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy248;
			if (yych == 'e') goto yy248;
			goto yy58;
yy198:
			yych = *++YYCURSOR;
			if (yych == 'O') goto yy249;
			if (yych == 'o') goto yy249;
			goto yy58;
yy199:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy251;
			if (yych == 'n') goto yy251;
			goto yy58;
yy200:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy253;
			if (yych == 't') goto yy253;
			goto yy58;
yy201:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy255;
			if (yych == 'e') goto yy255;
			goto yy58;
yy202:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy257;
			if (yych == 'i') goto yy257;
			goto yy58;
yy203:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 205 "scanner.re" */
			{
			token->opcode = PHQL_T_NOT;
			return 0;
		}
/* #line 1530 "scanner.c" */
yy205:
			yych = *++YYCURSOR;
			if (yych == 'L') goto yy258;
			if (yych == 'l') goto yy258;
			goto yy58;
yy206:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy260;
			if (yych == 's') goto yy260;
			goto yy58;
yy207:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy261;
			if (yych == 'e') goto yy261;
			goto yy58;
yy208:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy262;
			if (yych == 'e') goto yy262;
			goto yy58;
yy209:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy263;
			if (yych == 'h') goto yy263;
			goto yy58;
yy210:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy264;
			if (yych == 'e') goto yy264;
			goto yy58;
yy211:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 120 "scanner.re" */
			{
			token->opcode = PHQL_T_SET;
			return 0;
		}
/* #line 1571 "scanner.c" */
yy213:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy265;
			if (yych == 'n') goto yy265;
			goto yy58;
yy214:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy267;
			if (yych == 'e') goto yy267;
			goto yy58;
yy215:
			yych = *++YYCURSOR;
			if (yych == 'A') goto yy269;
			if (yych == 'a') goto yy269;
			goto yy58;
yy216:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy270;
			if (yych == 'n') goto yy270;
			goto yy58;
yy217:
			yych = *++YYCURSOR;
			if (yych == 'U') goto yy271;
			if (yych == 'u') goto yy271;
			goto yy58;
yy218:
			yych = *++YYCURSOR;
			if (yych <= 'R') {
				if (yych == 'N') goto yy272;
				if (yych <= 'Q') goto yy58;
				goto yy274;
			} else {
				if (yych <= 'n') {
					if (yych <= 'm') goto yy58;
					goto yy272;
				} else {
					if (yych == 'r') goto yy274;
					goto yy58;
				}
			}
yy219:
			yych = *++YYCURSOR;
			if (yych == 'H') goto yy275;
			if (yych == 'h') goto yy275;
			goto yy58;
yy220:
			++YYCURSOR;
/* #line 399 "scanner.re" */
			{
			token->opcode = PHQL_T_IDENTIFIER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 1627 "scanner.c" */
yy222:
			++YYCURSOR;
/* #line 107 "scanner.re" */
			{
			token->opcode = PHQL_T_BPLACEHOLDER;
			token->value = estrndup(q, YYCURSOR - q - 1);
			token->len = YYCURSOR - q - 1;
			q = YYCURSOR;
			return 0;
		}
/* #line 1638 "scanner.c" */
yy224:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy277;
			if (yych == 'n') goto yy277;
			goto yy58;
yy225:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy278;
			if (yych == 'e') goto yy278;
			goto yy58;
yy226:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 335 "scanner.re" */
			{
			token->opcode = PHQL_T_CASE;
			return 0;
		}
/* #line 1659 "scanner.c" */
yy228:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 305 "scanner.re" */
			{
			token->opcode = PHQL_T_CAST;
			return 0;
		}
/* #line 1670 "scanner.c" */
yy230:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy279;
			if (yych == 'e') goto yy279;
			goto yy58;
yy231:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy280;
			if (yych == 's') goto yy280;
			goto yy58;
yy232:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy282;
			if (yych == 't') goto yy282;
			goto yy58;
yy233:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 180 "scanner.re" */
			{
			token->opcode = PHQL_T_DESC;
			return 0;
		}
/* #line 1696 "scanner.c" */
yy235:
			yych = *++YYCURSOR;
			if (yych == 'I') goto yy283;
			if (yych == 'i') goto yy283;
			goto yy58;
yy236:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 350 "scanner.re" */
			{
			token->opcode = PHQL_T_ELSE;
			return 0;
		}
/* #line 1712 "scanner.c" */
yy238:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy284;
			if (yych == 't') goto yy284;
			goto yy58;
yy239:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy285;
			if (yych == 'e') goto yy285;
			goto yy58;
yy240:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 130 "scanner.re" */
			{
			token->opcode = PHQL_T_FROM;
			return 0;
		}
/* #line 1733 "scanner.c" */
yy242:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 275 "scanner.re" */
			{
			token->opcode = PHQL_T_FULL;
			return 0;
		}
/* #line 1744 "scanner.c" */
yy244:
			yych = *++YYCURSOR;
			if (yych == 'P') goto yy287;
			if (yych == 'p') goto yy287;
			goto yy58;
yy245:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy289;
			if (yych == 'n') goto yy289;
			goto yy58;
yy246:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy290;
			if (yych == 'e') goto yy290;
			goto yy58;
yy247:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy292;
			if (yych == 'r') goto yy292;
			goto yy58;
yy248:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy294;
			if (yych == 'r') goto yy294;
			goto yy58;
yy249:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 145 "scanner.re" */
			{
			token->opcode = PHQL_T_INTO;
			return 0;
		}
/* #line 1780 "scanner.c" */
yy251:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 245 "scanner.re" */
			{
			token->opcode = PHQL_T_JOIN;
			return 0;
		}
/* #line 1791 "scanner.c" */
yy253:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 255 "scanner.re" */
			{
			token->opcode = PHQL_T_LEFT;
			return 0;
		}
/* #line 1802 "scanner.c" */
yy255:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 220 "scanner.re" */
			{
			token->opcode = PHQL_T_LIKE;
			return 0;
		}
/* #line 1813 "scanner.c" */
yy257:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy295;
			if (yych == 't') goto yy295;
			goto yy58;
yy258:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 285 "scanner.re" */
			{
			token->opcode = PHQL_T_NULL;
			return 0;
		}
/* #line 1829 "scanner.c" */
yy260:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy297;
			if (yych == 'e') goto yy297;
			goto yy58;
yy261:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy298;
			if (yych == 'r') goto yy298;
			goto yy58;
yy262:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy300;
			if (yych == 'r') goto yy300;
			goto yy58;
yy263:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy302;
			if (yych == 't') goto yy302;
			goto yy58;
yy264:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy304;
			if (yych == 'c') goto yy304;
			goto yy58;
yy265:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 345 "scanner.re" */
			{
			token->opcode = PHQL_T_THEN;
			return 0;
		}
/* #line 1865 "scanner.c" */
yy267:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 325 "scanner.re" */
			{
			token->opcode = PHQL_T_TRUE;
			return 0;
		}
/* #line 1876 "scanner.c" */
yy269:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy305;
			if (yych == 't') goto yy305;
			goto yy58;
yy270:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy306;
			if (yych == 'g') goto yy306;
			goto yy58;
yy271:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy308;
			if (yych == 'e') goto yy308;
			goto yy58;
yy272:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 340 "scanner.re" */
			{
			token->opcode = PHQL_T_WHEN;
			return 0;
		}
/* #line 1902 "scanner.c" */
yy274:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy309;
			if (yych == 'e') goto yy309;
			goto yy58;
yy275:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 365 "scanner.re" */
			{
			token->opcode = PHQL_T_WITH;
			return 0;
		}
/* #line 1918 "scanner.c" */
yy277:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy311;
			if (yych == 's') goto yy311;
			goto yy58;
yy278:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy312;
			if (yych == 'e') goto yy312;
			goto yy58;
yy279:
			yych = *++YYCURSOR;
			if (yych == 'R') goto yy313;
			if (yych == 'r') goto yy313;
			goto yy58;
yy280:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 265 "scanner.re" */
			{
			token->opcode = PHQL_T_CROSS;
			return 0;
		}
/* #line 1944 "scanner.c" */
yy282:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy314;
			if (yych == 'e') goto yy314;
			goto yy58;
yy283:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy316;
			if (yych == 'n') goto yy316;
			goto yy58;
yy284:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy317;
			if (yych == 's') goto yy317;
			goto yy58;
yy285:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 330 "scanner.re" */
			{
			token->opcode = PHQL_T_FALSE;
			return 0;
		}
/* #line 1970 "scanner.c" */
yy287:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 185 "scanner.re" */
			{
			token->opcode = PHQL_T_GROUP;
			return 0;
		}
/* #line 1981 "scanner.c" */
yy289:
			yych = *++YYCURSOR;
			if (yych == 'G') goto yy319;
			if (yych == 'g') goto yy319;
			goto yy58;
yy290:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 225 "scanner.re" */
			{
			token->opcode = PHQL_T_ILIKE;
			return 0;
		}
/* #line 1997 "scanner.c" */
yy292:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 250 "scanner.re" */
			{
			token->opcode = PHQL_T_INNER;
			return 0;
		}
/* #line 2008 "scanner.c" */
yy294:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy321;
			if (yych == 't') goto yy321;
			goto yy58;
yy295:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 195 "scanner.re" */
			{
			token->opcode = PHQL_T_LIMIT;
			return 0;
		}
/* #line 2024 "scanner.c" */
yy297:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy323;
			if (yych == 't') goto yy323;
			goto yy58;
yy298:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 165 "scanner.re" */
			{
			token->opcode = PHQL_T_ORDER;
			return 0;
		}
/* #line 2040 "scanner.c" */
yy300:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 270 "scanner.re" */
			{
			token->opcode = PHQL_T_OUTER;
			return 0;
		}
/* #line 2051 "scanner.c" */
yy302:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 260 "scanner.re" */
			{
			token->opcode = PHQL_T_RIGHT;
			return 0;
		}
/* #line 2062 "scanner.c" */
yy304:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy325;
			if (yych == 't') goto yy325;
			goto yy58;
yy305:
			yych = *++YYCURSOR;
			if (yych == 'E') goto yy327;
			if (yych == 'e') goto yy327;
			goto yy58;
yy306:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 315 "scanner.re" */
			{
			token->opcode = PHQL_T_USING;
			return 0;
		}
/* #line 2083 "scanner.c" */
yy308:
			yych = *++YYCURSOR;
			if (yych == 'S') goto yy329;
			if (yych == 's') goto yy329;
			goto yy58;
yy309:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 155 "scanner.re" */
			{
			token->opcode = PHQL_T_WHERE;
			return 0;
		}
/* #line 2099 "scanner.c" */
yy311:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy331;
			if (yych == 't') goto yy331;
			goto yy58;
yy312:
			yych = *++YYCURSOR;
			if (yych == 'N') goto yy333;
			if (yych == 'n') goto yy333;
			goto yy58;
yy313:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy335;
			if (yych == 't') goto yy335;
			goto yy58;
yy314:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 125 "scanner.re" */
			{
			token->opcode = PHQL_T_DELETE;
			return 0;
		}
/* #line 2125 "scanner.c" */
yy316:
			yych = *++YYCURSOR;
			if (yych == 'C') goto yy337;
			if (yych == 'c') goto yy337;
			goto yy58;
yy317:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 320 "scanner.re" */
			{
			token->opcode = PHQL_T_EXISTS;
			return 0;
		}
/* #line 2141 "scanner.c" */
yy319:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 190 "scanner.re" */
			{
			token->opcode = PHQL_T_HAVING;
			return 0;
		}
/* #line 2152 "scanner.c" */
yy321:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 140 "scanner.re" */
			{
			token->opcode = PHQL_T_INSERT;
			return 0;
		}
/* #line 2163 "scanner.c" */
yy323:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 200 "scanner.re" */
			{
			token->opcode = PHQL_T_OFFSET;
			return 0;
		}
/* #line 2174 "scanner.c" */
yy325:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 160 "scanner.re" */
			{
			token->opcode = PHQL_T_SELECT;
			return 0;
		}
/* #line 2185 "scanner.c" */
yy327:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 115 "scanner.re" */
			{
			token->opcode = PHQL_T_UPDATE;
			return 0;
		}
/* #line 2196 "scanner.c" */
yy329:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 150 "scanner.re" */
			{
			token->opcode = PHQL_T_VALUES;
			return 0;
		}
/* #line 2207 "scanner.c" */
yy331:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 230 "scanner.re" */
			{
			token->opcode = PHQL_T_AGAINST;
			return 0;
		}
/* #line 2218 "scanner.c" */
yy333:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 300 "scanner.re" */
			{
			token->opcode = PHQL_T_BETWEEN;
			return 0;
		}
/* #line 2229 "scanner.c" */
yy335:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 310 "scanner.re" */
			{
			token->opcode = PHQL_T_CONVERT;
			return 0;
		}
/* #line 2240 "scanner.c" */
yy337:
			yych = *++YYCURSOR;
			if (yych == 'T') goto yy338;
			if (yych != 't') goto yy58;
yy338:
			++YYCURSOR;
			if (yybm[0+(yych = *YYCURSOR)] & 4) {
				goto yy57;
			}
/* #line 290 "scanner.re" */
			{
			token->opcode = PHQL_T_DISTINCT;
			return 0;
		}
/* #line 2255 "scanner.c" */
		}
/* #line 562 "scanner.re" */

	}

	return status;
}
