/* Generated by re2c 0.16 on Thu Oct 20 09:20:34 2016 */
/* #line 1 "scanner.re" */

/*
  +------------------------------------------------------------------------+
  | Phalcon Framework                                                      |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2014 Phalcon Team (http://www.phalconphp.com)       |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file docs/LICENSE.txt.                        |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  +------------------------------------------------------------------------+
*/

#include "php_phalcon.h"

#include "annotations/scanner.h"

#define JJCTYPE unsigned char
#define JJCURSOR (s->start)
#define JJLIMIT (s->end)
#define JJMARKER q

int phannot_get_token(phannot_scanner_state *s, phannot_scanner_token *token) {

	char next, *q = JJCURSOR, *start = JJCURSOR;
	int status = PHANNOT_SCANNER_RETCODE_IMPOSSIBLE;

	while (PHANNOT_SCANNER_RETCODE_IMPOSSIBLE == status) {

		if (s->mode == PHANNOT_MODE_RAW) {

			if (*JJCURSOR == '\n') {
				s->active_line++;
			}

			next = *(JJCURSOR+1);

			if (*JJCURSOR == '\0' || *JJCURSOR == '@') {
				if ((next >= 'A' && next <= 'Z') || (next >= 'a' && next <= 'z')) {
					s->mode = PHANNOT_MODE_ANNOTATION;
					continue;
				}
			}

			++JJCURSOR;
			token->opcode = PHANNOT_T_IGNORE;
			return 0;

		} else {

		
/* #line 61 "scanner.c" */
		{
			JJCTYPE jjch;
			unsigned int jjaccept = 0;
			static const unsigned char jjbm[] = {
				  0, 192, 192, 192, 192, 192, 192, 192, 
				192, 200, 192, 192, 192, 200, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				200, 192, 128, 192, 192, 192, 192,  64, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				240, 240, 240, 240, 240, 240, 240, 240, 
				240, 240, 192, 192, 192, 192, 192, 192, 
				192, 224, 224, 224, 224, 224, 224, 224, 
				224, 224, 224, 224, 224, 224, 224, 224, 
				224, 224, 224, 224, 224, 224, 224, 224, 
				224, 224, 224, 192,   0, 192, 192, 224, 
				192, 224, 224, 224, 224, 224, 224, 224, 
				224, 224, 224, 224, 224, 224, 224, 224, 
				224, 224, 224, 224, 224, 224, 224, 224, 
				224, 224, 224, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
				192, 192, 192, 192, 192, 192, 192, 192, 
			};
			jjch = *JJCURSOR;
			if (jjbm[0+jjch] & 8) {
				goto jj6;
			}
			if (jjch <= 'F') {
				if (jjch <= '+') {
					if (jjch <= '"') {
						if (jjch <= 0x08) {
							if (jjch >= 0x01) goto jj4;
						} else {
							if (jjch <= '\n') goto jj9;
							if (jjch <= '!') goto jj4;
							goto jj11;
						}
					} else {
						if (jjch <= '\'') {
							if (jjch <= '&') goto jj4;
							goto jj12;
						} else {
							if (jjch <= '(') goto jj13;
							if (jjch <= ')') goto jj15;
							goto jj4;
						}
					}
				} else {
					if (jjch <= ':') {
						if (jjch <= '-') {
							if (jjch <= ',') goto jj17;
							goto jj19;
						} else {
							if (jjch <= '/') goto jj4;
							if (jjch <= '9') goto jj20;
							goto jj23;
						}
					} else {
						if (jjch <= '?') {
							if (jjch == '=') goto jj25;
							goto jj4;
						} else {
							if (jjch <= '@') goto jj27;
							if (jjch <= 'E') goto jj29;
							goto jj32;
						}
					}
				}
			} else {
				if (jjch <= '`') {
					if (jjch <= 'Z') {
						if (jjch <= 'N') {
							if (jjch <= 'M') goto jj29;
							goto jj33;
						} else {
							if (jjch == 'T') goto jj34;
							goto jj29;
						}
					} else {
						if (jjch <= ']') {
							if (jjch <= '[') goto jj35;
							if (jjch <= '\\') goto jj37;
							goto jj38;
						} else {
							if (jjch == '_') goto jj29;
							goto jj4;
						}
					}
				} else {
					if (jjch <= 's') {
						if (jjch <= 'f') {
							if (jjch <= 'e') goto jj29;
							goto jj32;
						} else {
							if (jjch == 'n') goto jj33;
							goto jj29;
						}
					} else {
						if (jjch <= '{') {
							if (jjch <= 't') goto jj34;
							if (jjch <= 'z') goto jj29;
							goto jj40;
						} else {
							if (jjch == '}') goto jj42;
							goto jj4;
						}
					}
				}
			}
			++JJCURSOR;
/* #line 173 "scanner.re" */
			{
			status = PHANNOT_SCANNER_RETCODE_EOF;
			break;
		}
/* #line 191 "scanner.c" */
jj4:
			++JJCURSOR;
jj5:
/* #line 178 "scanner.re" */
			{
			status = PHANNOT_SCANNER_RETCODE_ERR;
			break;
		}
/* #line 200 "scanner.c" */
jj6:
			++JJCURSOR;
			jjch = *JJCURSOR;
			if (jjbm[0+jjch] & 8) {
				goto jj6;
			}
/* #line 162 "scanner.re" */
			{
			token->opcode = PHANNOT_T_IGNORE;
			return 0;
		}
/* #line 212 "scanner.c" */
jj9:
			++JJCURSOR;
/* #line 167 "scanner.re" */
			{
			s->active_line++;
			token->opcode = PHANNOT_T_IGNORE;
			return 0;
		}
/* #line 221 "scanner.c" */
jj11:
			jjaccept = 0;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch <= 0x00) goto jj5;
			goto jj45;
jj12:
			jjaccept = 0;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch <= 0x00) goto jj5;
			goto jj51;
jj13:
			++JJCURSOR;
/* #line 112 "scanner.re" */
			{
			token->opcode = PHANNOT_T_PARENTHESES_OPEN;
			return 0;
		}
/* #line 239 "scanner.c" */
jj15:
			++JJCURSOR;
/* #line 117 "scanner.re" */
			{
			token->opcode = PHANNOT_T_PARENTHESES_CLOSE;
			return 0;
		}
/* #line 247 "scanner.c" */
jj17:
			++JJCURSOR;
/* #line 157 "scanner.re" */
			{
			token->opcode = PHANNOT_T_COMMA;
			return 0;
		}
/* #line 255 "scanner.c" */
jj19:
			jjch = *++JJCURSOR;
			if (jjbm[0+jjch] & 16) {
				goto jj20;
			}
			goto jj5;
jj20:
			jjaccept = 1;
			JJMARKER = ++JJCURSOR;
			jjch = *JJCURSOR;
			if (jjbm[0+jjch] & 16) {
				goto jj20;
			}
			if (jjch == '.') goto jj53;
jj22:
/* #line 62 "scanner.re" */
			{
			token->opcode = PHANNOT_T_INTEGER;
			token->value = estrndup(start, JJCURSOR - start);
			token->len = JJCURSOR - start;
			q = JJCURSOR;
			return 0;
		}
/* #line 279 "scanner.c" */
jj23:
			++JJCURSOR;
/* #line 152 "scanner.re" */
			{
			token->opcode = PHANNOT_T_COLON;
			return 0;
		}
/* #line 287 "scanner.c" */
jj25:
			++JJCURSOR;
/* #line 147 "scanner.re" */
			{
			token->opcode = PHANNOT_T_EQUALS;
			return 0;
		}
/* #line 295 "scanner.c" */
jj27:
			++JJCURSOR;
/* #line 142 "scanner.re" */
			{
			token->opcode = PHANNOT_T_AT;
			return 0;
		}
/* #line 303 "scanner.c" */
jj29:
			jjaccept = 2;
			JJMARKER = ++JJCURSOR;
			jjch = *JJCURSOR;
jj30:
			if (jjbm[0+jjch] & 32) {
				goto jj29;
			}
			if (jjch == '\\') goto jj54;
jj31:
/* #line 104 "scanner.re" */
			{
			token->opcode = PHANNOT_T_IDENTIFIER;
			token->value = estrndup(start, JJCURSOR - start);
			token->len = JJCURSOR - start;
			q = JJCURSOR;
			return 0;
		}
/* #line 322 "scanner.c" */
jj32:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'A') goto jj55;
			if (jjch == 'a') goto jj55;
			goto jj30;
jj33:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'U') goto jj56;
			if (jjch == 'u') goto jj56;
			goto jj30;
jj34:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'R') goto jj57;
			if (jjch == 'r') goto jj57;
			goto jj30;
jj35:
			++JJCURSOR;
/* #line 132 "scanner.re" */
			{
			token->opcode = PHANNOT_T_SBRACKET_OPEN;
			return 0;
		}
/* #line 348 "scanner.c" */
jj37:
			jjch = *++JJCURSOR;
			if (jjch <= '^') {
				if (jjch <= '@') goto jj5;
				if (jjch <= 'Z') goto jj29;
				goto jj5;
			} else {
				if (jjch == '`') goto jj5;
				if (jjch <= 'z') goto jj29;
				goto jj5;
			}
jj38:
			++JJCURSOR;
/* #line 137 "scanner.re" */
			{
			token->opcode = PHANNOT_T_SBRACKET_CLOSE;
			return 0;
		}
/* #line 367 "scanner.c" */
jj40:
			++JJCURSOR;
/* #line 122 "scanner.re" */
			{
			token->opcode = PHANNOT_T_BRACKET_OPEN;
			return 0;
		}
/* #line 375 "scanner.c" */
jj42:
			++JJCURSOR;
/* #line 127 "scanner.re" */
			{
			token->opcode = PHANNOT_T_BRACKET_CLOSE;
			return 0;
		}
/* #line 383 "scanner.c" */
jj44:
			++JJCURSOR;
			jjch = *JJCURSOR;
jj45:
			if (jjbm[0+jjch] & 64) {
				goto jj44;
			}
			if (jjch <= 0x00) goto jj46;
			if (jjch <= '"') goto jj47;
			goto jj49;
jj46:
			JJCURSOR = JJMARKER;
			if (jjaccept <= 2) {
				if (jjaccept <= 1) {
					if (jjaccept == 0) {
						goto jj5;
					} else {
						goto jj22;
					}
				} else {
					goto jj31;
				}
			} else {
				if (jjaccept <= 4) {
					if (jjaccept == 3) {
						goto jj66;
					} else {
						goto jj68;
					}
				} else {
					goto jj70;
				}
			}
jj47:
			++JJCURSOR;
/* #line 95 "scanner.re" */
			{
			token->opcode = PHANNOT_T_STRING;
			token->value = estrndup(q, JJCURSOR - q - 1);
			token->len = JJCURSOR - q - 1;
			q = JJCURSOR;
			return 0;
		}
/* #line 427 "scanner.c" */
jj49:
			++JJCURSOR;
			jjch = *JJCURSOR;
			if (jjch == '\n') goto jj46;
			goto jj44;
jj50:
			++JJCURSOR;
			jjch = *JJCURSOR;
jj51:
			if (jjbm[0+jjch] & 128) {
				goto jj50;
			}
			if (jjch <= 0x00) goto jj46;
			if (jjch <= '\'') goto jj47;
			++JJCURSOR;
			jjch = *JJCURSOR;
			if (jjch == '\n') goto jj46;
			goto jj50;
jj53:
			jjch = *++JJCURSOR;
			if (jjch <= '/') goto jj46;
			if (jjch <= '9') goto jj58;
			goto jj46;
jj54:
			++JJCURSOR;
			jjch = *JJCURSOR;
			if (jjch <= '^') {
				if (jjch <= '@') goto jj46;
				if (jjch <= 'Z') goto jj29;
				goto jj46;
			} else {
				if (jjch == '`') goto jj46;
				if (jjch <= 'z') goto jj29;
				goto jj46;
			}
jj55:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'L') goto jj61;
			if (jjch == 'l') goto jj61;
			goto jj30;
jj56:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'L') goto jj62;
			if (jjch == 'l') goto jj62;
			goto jj30;
jj57:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'U') goto jj63;
			if (jjch == 'u') goto jj63;
			goto jj30;
jj58:
			++JJCURSOR;
			jjch = *JJCURSOR;
			if (jjch <= '/') goto jj60;
			if (jjch <= '9') goto jj58;
jj60:
/* #line 71 "scanner.re" */
			{
			token->opcode = PHANNOT_T_DOUBLE;
			token->value = estrndup(start, JJCURSOR - start);
			token->len = JJCURSOR - start;
			q = JJCURSOR;
			return 0;
		}
/* #line 495 "scanner.c" */
jj61:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'S') goto jj64;
			if (jjch == 's') goto jj64;
			goto jj30;
jj62:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'L') goto jj65;
			if (jjch == 'l') goto jj65;
			goto jj30;
jj63:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'E') goto jj67;
			if (jjch == 'e') goto jj67;
			goto jj30;
jj64:
			jjaccept = 2;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjch == 'E') goto jj69;
			if (jjch == 'e') goto jj69;
			goto jj30;
jj65:
			jjaccept = 3;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjbm[0+jjch] & 32) {
				goto jj29;
			}
			if (jjch == '\\') goto jj54;
jj66:
/* #line 79 "scanner.re" */
			{
			token->opcode = PHANNOT_T_NULL;
			return 0;
		}
/* #line 533 "scanner.c" */
jj67:
			jjaccept = 4;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjbm[0+jjch] & 32) {
				goto jj29;
			}
			if (jjch == '\\') goto jj54;
jj68:
/* #line 89 "scanner.re" */
			{
			token->opcode = PHANNOT_T_TRUE;
			return 0;
		}
/* #line 547 "scanner.c" */
jj69:
			jjaccept = 5;
			jjch = *(JJMARKER = ++JJCURSOR);
			if (jjbm[0+jjch] & 32) {
				goto jj29;
			}
			if (jjch == '\\') goto jj54;
jj70:
/* #line 84 "scanner.re" */
			{
			token->opcode = PHANNOT_T_FALSE;
			return 0;
		}
/* #line 561 "scanner.c" */
		}
/* #line 183 "scanner.re" */


		}
	}

	return status;
}
